title: Master's Thesis
description: Multi-Factor Authentication in Comparison with the Web Authentication API
logo: /assets/img/logo.png
encoding: UTF-8
theme: jekyll-theme-minimal
future: true
timezone: Europe/Berlin
