(function () {
    var a = {};
    a[483] = {
        link: {
            linkIcon: "https://c.evidon.com/pub/icong1.png",
            linkStyle: "cursor:pointer;text-decoration:none;font-size:11pt;color:#000101;",
            mobileLinkIcon: "https://c.evidon.com/pub/icong1.png",
            mobileLinkStyle: "cursor:pointer;text-decoration:none;font-size:11pt;color:#000101;",
            mobileShowIcon: true,
            showIcon: true
        },
        button: {
            buttonIcon: "https://c.evidon.com/pub/icong2.png",
            buttonStyle: "position:fixed;padding:0 10px;border:1px solid #000101;cursor:pointer;line-height:36px;text-decoration:none;background:#ffffff;font-size:10pt;color:#000101;bottom:0;left:0;z-index:2147483600;",
            mobileButtonIcon: "https://c.evidon.com/pub/icong2.png",
            mobileButtonStyle: "position:fixed;padding:0 10px;border:1px solid #000101;cursor:pointer;line-height:36px;text-decoration:none;background:#ffffff;font-size:10pt;color:#000101;bottom:0;left:0;z-index:2147483600;",
            mobileShowIcon: true,
            mobileShowText: true,
            showIcon: true,
            showText: true
        },
        banner: {
            bannerStyle: "position:absolute;display:block;width:100%;background:#ffffff;padding:4px;font-size:14px;color:#000000;bottom:0;border-top:1px solid #aaaaaa;border:1px solid #000101;",
            titleStyle: "display:block;font-size:18px;text-align:center;margin:8px 18px;",
            messageStyle: "display:inline-block;margin:12px 18px auto;font-family:Arial, sans-serif;font-weight:300;color:#000101;font-size:14px;line-height:1.5;padding:6px 0px 12px;",
            showAcceptButton: true,
            acceptButtonStyle: "display:block;float:right;margin:16px 24px;border:0px;background:#000101;color:#ffffff!important;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;text-shadow:none;height:auto;",
            showCloseIcon: false,
            closeIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:2;",
            closeIconStroke: "#000000",
            closeIconThickness: "2",
            showIcon: false,
            iconStyle: "position:absolute;top:4px;left:4px;width:24px;height:24px;",
            showOptionButton: true,
            optionButtonStyle: "display:block;float:left;margin:16px 24px;border:0px;background:#000101;color:#ffffff!important;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;text-shadow:none;height:auto;",
            showTitle: false,
            showDeclineButton: false,
            declineButtonStyle: "display:inline;border:0;background:#000000;color:#ffffff;padding:8px 22px;cursor:pointer;border-radius:4px;",
            backgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#dddddd;opacity:.5;",
            showBackground: false,
            mobileBannerStyle: "position:absolute;display:block;width:100%;background:#ffffff;padding:4px;font-size:14px;color:#000000;bottom:0;border-top:1px solid #aaaaaa;",
            mobileTitleStyle: "display:block;font-size:18px;text-align:center;margin:8px 12px;",
            mobileMessageStyle: "display:inline-block;margin:12px 18px auto;font-family:Arial, sans-serif;font-weight:300;color:#000101;font-size:14px;line-height:1.5;padding:6px 0px 12px;",
            mobileShowAcceptButton: true,
            mobileAcceptButtonStyle: "display:block;margin:16px 20px 16px 0px;border:0;background:#000000;color:#ffffff;padding:10px 25px;cursor:pointer;font-family:Arial, sans-serif;font-size:14px;",
            mobileShowCloseIcon: false,
            mobileCloseIconStyle: "position:absolute;top:4px;right:4px;height:12px;width:12px;stroke:#000000;stroke-width:2;",
            mobileCloseIconStroke: "#000000",
            mobileCloseIconThickness: "2",
            mobileShowIcon: false,
            mobileIconStyle: "position:absolute;top:4px;left:4px;width:16px;height:16px;",
            mobileShowCollapseMessage: false,
            mobileCollapseMessageStyle: "display:block;font-size:16px;text-align:center;padding:12px;cursor:pointer;",
            mobileShowOptionButton: true,
            mobileOptionButtonStyle: "display:block;float:left;margin:16px 0px 16px 20px;border:0px;background:#000101;color:#ffffff;padding:10px 25px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;",
            mobileShowTitle: false,
            mobileShowDeclineButton: false,
            mobileDeclineButtonStyle: "display:block;float:right;margin:16px 20px 16px 0px;border:0px;background:#000101;color:#ffffff;padding:10px 25px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;",
            mobileBackgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#dddddd;opacity:.5;",
            mobileShowBackground: false,
            bannerIcon: null,
            mobileBannerIcon: null
        },
        barrier: {
            bannerStyle: "position:relative;display:block;margin:40px auto;background:#ffffff;width:60%;padding:12px;",
            titleStyle: "display:block;text-align:center;font-size:1.5rem;padding:4px 0;",
            messageStyle: "display:block;font-size:1rem;vertical-align:top;padding:16px 8px;line-height:1.4;",
            showCloseIcon: false,
            closeIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:0;",
            closeIconStroke: "#000000",
            closeIconThickness: "0",
            acceptButtonStyle: "display:block;margin:12px auto;padding:6px 8px;border:1px solid #000000;background:#111111;color:#ffffff;font-size:1.1rem;",
            acceptMessageStyle: "display:block;margin:14px 0 8px 0;font-size:1rem;padding:0 12px;line-height:1.5;",
            cookieButtonStyle: "display:block;border:0 solid #000000;background:transparent;font-size:1.1rem;margin:0 2px;text-decoration:underline;",
            cookieMessageStyle: "display:block;font-size:1rem;padding:12px 8px;line-height:1.4;",
            logoStyle: "display:block;width:;height:40px;margin:8px auto;",
            showCookieButtonIcon: true,
            showDeclineButton: false,
            declineButtonStyle: "display:block;margin:12px auto;padding:6px 8px;border:1px solid black;background:#111111;color:white;font-size:1.1rem;",
            mobileBannerStyle: "position:relative;display:block;margin:20px auto;background:#ffffff;width:100%;padding:12px;",
            mobileTitleStyle: "display:block;text-align:center;font-size:18px;padding:4px 0;",
            mobileMessageStyle: "display:block;font-size:12px;vertical-align:top;padding:16px 8px;line-height:1.4;",
            mobileShowCloseIcon: false,
            mobileCloseIconStyle: "position:absolute;top:4px;right:4px;height:12px;width:12px;stroke:#000000;stroke-width:0;",
            mobileCloseIconStroke: "#000000",
            mobileCloseIconThickness: "0",
            mobileAcceptButtonStyle: "display:block;margin:12px auto;padding:12px;border:1px solid #000000;background:#111111;color:#ffffff;font-size:16px;",
            mobileAcceptMessageStyle: "display:block;margin:14px 0 8px 0;font-size:12px;padding:0 12px;line-height:1.4;",
            mobileCookieButtonStyle: "display:block;border:0 solid #000000;background:transparent;font-size:14px;margin:0 2px;text-decoration:underline;",
            mobileCookieMessageStyle: "display:block;font-size:12px;padding:12px 8px;line-height:1.4;",
            mobileLogoStyle: "display:block;width:;margin:8px auto;height:40px;",
            mobileShowCookieButtonIcon: false,
            mobileShowOptionButton: "null",
            mobileShowDeclineButton: false,
            mobileDeclineButtonStyle: "display:block;margin:12px auto;padding:12px;border:1px solid black;background:#111111;color:white;font-size:16px;",
            backgroundStyle: "null",
            backgroundStyle: "",
            logo: null,
            mobileLogo: null,
            cookieButtonIcon: null,
            mobileCookieButtonIcon: null
        },
        l2: {
            overlayStyle: "display:block;position:absolute;top:10%;left:15%;width:70%;padding:18px;background:#f5f5f5;box-shadow:0px 2px 12px rgba(0,0,0,.5);",
            titleStyle: "display:block;text-align:center;margin:6px auto;font-size:20px;font-weight:300;font-family:Open Sans;color:#000000;",
            showTitle: true,
            messageStyle: "display:block;margin:0px auto 6px;font-size:13px;line-height:16px;font-family:Open Sans;font-weight:300;color:#4a4a4a;",
            subtitleStyle: "display:block;font-size:14px;font-weight:700;font-family:Open Sans;color:#4a4a4a;margin:6px 0 0;line-height:;",
            closeIconStyle: "display:block;position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#9b9b9b;stroke-width:3;cursor:pointer;",
            logoStyle: "display:block;margin:8px auto;width:136;height:43;color:white;",
            linkStyle: "display:block;color:#205493;text-decoration:none;font-size:13px;font-weight:600;text-align:left;margin:10px 0;font-family:Open Sans;",
            backgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#4a4a4a;opacity:.51;",
            showBackground: true,
            categoryHeaderStyle: "color:black;font-size:12px;",
            categoryDescriptionStyle: "color:#333333;font-size:12px;",
            showDeclineButton: true,
            showGlobalPrefButton: true,
            primaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#f2f2f2;background:#205493;cursor:pointer;border:2px solid transparent;float:right;",
            secondaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#333333;background:#f3f3f3;cursor:pointer;border:2px solid transparent;float:right;",
            tertiaryButtonStyle: "margin:2px auto;padding:4px 8px;color:#333333;cursor:pointer;border:2px solid transparent;font-size:11px;",
            backButtonStyle: "color:#00AEF0;text-decoration:none;font-size:12px;",
            mobileOverlayStyle: "display:block;position:absolute;top:1%;width:100%;padding:18px;background:#f5f5f5;",
            mobileTitleStyle: "display:block;text-align:center;margin:6px auto;font-size:16px;font-weight:300;",
            mobileShowTitle: true,
            mobileMessageStyle: "display:block;margin:0px auto 6px;font-size:13px;line-height:16px;",
            mobileSubtitleStyle: "display:block;font-size:14px;font-weight:700;margin:6px 0 0px;",
            mobileCloseIconStyle: "display:block;position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#9b9b9b;stroke-width:3;cursor:pointer;",
            mobileLogoStyle: "display:block;margin:8px auto;width:136px;height:43px;color:white;",
            mobileLinkStyle: "display:block;color:#205493;text-decoration:none;font-size:13px;font-weight:600;text-align:left;margin:10px 0;font-family:Open Sans;",
            mobileBackgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#4a4a4a;",
            mobileShowBackground: true,
            mobileCategoryHeaderStyle: "color:black;font-size:12px;",
            mobileCategoryDescriptionStyle: "color:#333333;font-size:12px;",
            mobileShowDeclineButton: true,
            mobileShowGlobalPrefButton: true,
            mobilePrimaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#f2f2f2;background:#205493;cursor:pointer;border:2px solid transparent;float:right;",
            mobileSecondaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#333333;background:#f3f3f3;cursor:pointer;border:2px solid transparent;float:right;",
            mobileTertiaryButtonStyle: "margin:2px auto;padding:4px 8px;color:#333333;cursor:pointer;border:2px solid transparent;font-size:11px;",
            mobileBackButtonStyle: "color:#00AEF0;text-decoration:none;font-size:12px;",
            logo: null,
            mobileLogo: null
        }
    }, a[484] = {
        link: {
            linkIcon: "https://c.evidon.com/pub/icong1.png",
            linkStyle: "cursor:pointer;text-decoration:none;font-size:10pt;color:#000000;",
            mobileLinkIcon: "https://c.evidon.com/pub/icong1.png",
            mobileLinkStyle: "cursor:pointer;text-decoration:none;font-size:10pt;color:#000000;",
            mobileShowIcon: true,
            showIcon: true
        },
        button: {
            buttonIcon: "https://c.evidon.com/pub/icong2.png",
            buttonStyle: "position:fixed;padding:0 10px;border:1px solid #d7d7d7;cursor:pointer;line-height:36px;text-decoration:none;background:#060606;font-size:10pt;color:#e6e6e6;bottom:4px;left:4px;border-radius:8px;",
            mobileButtonIcon: "https://c.evidon.com/pub/icong2.png",
            mobileButtonStyle: "position:fixed;padding:0 10px;border:1px solid #d7d7d7;cursor:pointer;line-height:36px;text-decoration:none;background:#060606;font-size:10pt;color:#e6e6e6;bottom:4px;left:4px;border-radius:8px;",
            mobileShowIcon: true,
            mobileShowText: true,
            showIcon: true,
            showText: true
        },
        banner: {
            bannerStyle: "position:fixed;display:block;width:100%;background:#ffffff;font-size:14px;color:#000000;bottom:0;z-index:2147000001;border:1px solid #000101;",
            titleStyle: "display:none;font-size:18px;text-align:left;margin:8px 18px;",
            messageStyle: "display:inline-block;margin:12px 18px auto;font-family:Arial, sans-serif;font-weight:300;color:#000101;font-size:14px;line-height:1.5;padding:6px 0px 12px;",
            showAcceptButton: true,
            acceptButtonStyle: "display:block;float:right;margin:16px 24px;border:0px;background:#000101;color:#ffffff!important;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;text-shadow:none;height:auto;",
            showCloseIcon: false,
            closeIconStyle: "position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#e6e6e6;stroke-width:2;",
            closeIconStroke: "#e6e6e6",
            closeIconThickness: "2",
            showIcon: false,
            iconStyle: "position:absolute;top:4px;left:4px;width:24px;height:24px;",
            showOptionButton: true,
            optionButtonStyle: "display:block;float:left;margin:16px 24px;border:0px;background:#000101;color:#ffffff!important;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;text-shadow:none;height:auto;",
            showTitle: false,
            showDeclineButton: false,
            declineButtonStyle: "display:inline;border:0;background:#000000;color:#ffffff;padding:8px 22px;cursor:pointer;border-radius:4px;",
            backgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#dddddd;opacity:.5;",
            showBackground: false,
            mobileBannerStyle: "position:fixed;display:block;width:100%;background:#ffffff;font-size:14px;color:#000000;bottom:0;z-index:2147000001;border:1px solid #000101;",
            mobileTitleStyle: "display:none;font-size:18px;text-align:left;margin:8px 18px;",
            mobileMessageStyle: "display:inline-block;margin:12px 18px auto;font-family:Arial, sans-serif;font-weight:300;color:#000101;font-size:14px;line-height:1.5;padding:6px 0px 12px;",
            mobileShowAcceptButton: true,
            mobileAcceptButtonStyle: "display:block;float:right;margin:16px 24px;border:0px;background:#000101;color:#ffffff!important;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;text-shadow:none;height:auto;",
            mobileShowCloseIcon: false,
            mobileCloseIconStyle: "position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#e6e6e6;stroke-width:2;",
            mobileCloseIconStroke: "#e6e6e6",
            mobileCloseIconThickness: "2",
            mobileShowIcon: false,
            mobileIconStyle: "position:absolute;top:4px;left:4px;width:24px;height:24px;",
            mobileShowCollapseMessage: false,
            mobileCollapseMessageStyle: "display:block;font-size:16px;text-align:center;padding:12px;cursor:pointer;",
            mobileShowOptionButton: true,
            mobileOptionButtonStyle: "display:block;float:left;margin:16px 24px;border:0px;background:#000101;color:#ffffff!important;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;text-shadow:none;height:auto;",
            mobileShowTitle: false,
            mobileShowDeclineButton: false,
            mobileDeclineButtonStyle: "display:inline;border:0;background:#000000;color:#ffffff;padding:8px 22px;cursor:pointer;border-radius:4px;",
            mobileBackgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#dddddd;opacity:.5;",
            mobileShowBackground: false,
            bannerIcon: null,
            mobileBannerIcon: null
        },
        barrier: {
            bannerStyle: "position:relative;display:block;margin:40px auto;background:#030303;width:60%;padding:12px;",
            titleStyle: "display:block;text-align:center;font-size:1.5rem;padding:4px 0;color:#e6e6e6;",
            messageStyle: "display:block;font-size:1rem;vertical-align:top;padding:16px 8px;line-height:1.4;color:#e6e6e6;",
            showCloseIcon: false,
            closeIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:0;",
            closeIconStroke: "#000000",
            closeIconThickness: "0",
            acceptButtonStyle: "display:block;margin:22px auto;padding:6px 18px;border:1px solid #565454;background:#393939;color:#ffffff;font-size:1.1rem;border-radius:8px;",
            acceptMessageStyle: "display:block;margin:14px 0 8px 0;font-size:1rem;padding:0 12px;line-height:1.5;color:#e6e6e6;",
            cookieButtonStyle: "display:block;border:0 solid #000000;background:transparent;font-size:1.1rem;margin:0 2px;text-decoration:underline;color:#e6e6e6;",
            cookieMessageStyle: "display:block;font-size:1rem;padding:12px 8px;line-height:1.4;color:#e6e6e6;",
            logoStyle: "display:block;width:;height:40px;margin:8px auto;",
            showCookieButtonIcon: true,
            showDeclineButton: false,
            declineButtonStyle: "display:block;margin:12px auto;padding:6px 8px;border:1px solid black;background:#111111;color:white;font-size:1.1rem;",
            mobileBannerStyle: "position:relative;display:block;margin:40px auto;background:#030303;width:100%;padding:12px;",
            mobileTitleStyle: "display:block;text-align:center;font-size:1.5rem;padding:4px 0;color:#e6e6e6;",
            mobileMessageStyle: "display:block;font-size:1rem;vertical-align:top;padding:16px 8px;line-height:1.4;color:#e6e6e6;",
            mobileShowCloseIcon: false,
            mobileCloseIconStyle: "position:absolute;top:4px;right:4px;height:12px;width:12px;stroke:#000000;stroke-width:0;",
            mobileCloseIconStroke: "#000000",
            mobileCloseIconThickness: "0",
            mobileAcceptButtonStyle: "display:block;margin:22px auto;padding:6px 18px;border:1px solid #565454;background:#393939;color:#ffffff;font-size:1.1rem;border-radius:8px;",
            mobileAcceptMessageStyle: "display:block;margin:14px 0 8px 0;font-size:1rem;padding:0 12px;line-height:1.5;color:#e6e6e6;",
            mobileCookieButtonStyle: "display:block;border:0 solid #000000;background:transparent;font-size:1.1rem;margin:0 2px;text-decoration:underline;color:#e6e6e6;",
            mobileCookieMessageStyle: "display:block;font-size:1rem;padding:12px 8px;line-height:1.4;color:#e6e6e6;",
            mobileLogoStyle: "display:block;width:;height:40px;margin:8px auto;",
            mobileShowCookieButtonIcon: false,
            mobileShowOptionButton: "null",
            mobileShowDeclineButton: false,
            mobileDeclineButtonStyle: "display:block;margin:12px auto;padding:12px;border:1px solid black;background:#111111;color:white;font-size:16px;",
            backgroundStyle: "background:#9a9a9a;opacity:.8;",
            backgroundStyle: "background:#9a9a9a;opacity:.8;",
            logo: null,
            mobileLogo: null,
            cookieButtonIcon: null,
            mobileCookieButtonIcon: null
        },
        l2: {
            overlayStyle: "display:block;position:absolute;top:10%;left:15%;width:70%;padding:18px;background:#2d2d2d;box-shadow:0 2px 12px rgba(0,0,0,.5);",
            titleStyle: "display:block;text-align:center;margin:6px auto;font-size:20px;font-weight:300;font-family:Open Sans;color:#f5f5f5;",
            showTitle: true,
            messageStyle: "display:block;margin:0px auto 6px;font-size:13px;line-height:16px;font-family:Open Sans;font-weight:300;color:#f5f5f5;",
            subtitleStyle: "display:block;font-size:14px;font-weight:600;margin:6px 0  0px;font-family:Open Sans;color:#f5f5f5;",
            closeIconStyle: "display:block;position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#f5f5f5;stroke-width:3;cursor:pointer;",
            logoStyle: "display:block;margin:8px auto;width:136px;height:45.33px;color:white;",
            linkStyle: "display:block;color:#3eccff;text-decoration:none;font-size:13px;font-weight:400;text-align:left;margin:10px 0;font-family:Open Sans;",
            backgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#fafafa;opacity:.6;",
            showBackground: true,
            categoryHeaderStyle: "color:black;font-size:12px;",
            categoryDescriptionStyle: "color:#333333;font-size:12px;",
            showDeclineButton: true,
            showGlobalPrefButton: true,
            primaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#f2f2f2;background:#205493;cursor:pointer;border:2px solid transparent;float:right;",
            secondaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#333333;background:#f3f3f3;cursor:pointer;border:2px solid transparent;float:right;",
            tertiaryButtonStyle: "margin:2px auto;padding:4px 8px;color:#333333;cursor:pointer;border:2px solid transparent;font-size:11px;",
            backButtonStyle: "color:#00AEF0;text-decoration:none;font-size:12px;",
            mobileOverlayStyle: "display:block;position:absolute;top:1%;padding:18px;background:#2d2d2d;width:100%;",
            mobileTitleStyle: "display:block;text-align:center;margin:6px auto;font-size:16px;font-weight:300;font-family:Open Sans;color:#f5f5f5;",
            mobileShowTitle: true,
            mobileMessageStyle: "display:block;margin:0px auto 6px;font-size:13px;line-height:16px;font-family:Open Sans;font-weight:300;color:#f5f5f5;",
            mobileSubtitleStyle: "display:block;font-size:14px;font-weight:700;margin:6px 0  0px;font-family:Open Sans;color:#f5f5f5;",
            mobileCloseIconStyle: "display:block;position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#f5f5f5;stroke-width:3;cursor:pointer;",
            mobileLogoStyle: "display:block;margin:8px auto;width:136px;height:45.333px;color:white;",
            mobileLinkStyle: "display:block;color:#3eccff;text-decoration:none;font-size:13px;font-weight:400;text-align:left;margin:10px 0;font-family:Open Sans;",
            mobileBackgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#fafafa;",
            mobileShowBackground: true,
            mobileCategoryHeaderStyle: "color:black;font-size:12px;",
            mobileCategoryDescriptionStyle: "color:#333333;font-size:12px;",
            mobileShowDeclineButton: true,
            mobileShowGlobalPrefButton: true,
            mobilePrimaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#f2f2f2;background:#205493;cursor:pointer;border:2px solid transparent;float:right;",
            mobileSecondaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#333333;background:#f3f3f3;cursor:pointer;border:2px solid transparent;float:right;",
            mobileTertiaryButtonStyle: "margin:2px auto;padding:4px 8px;color:#333333;cursor:pointer;border:2px solid transparent;font-size:11px;",
            mobileBackButtonStyle: "color:#00AEF0;text-decoration:none;font-size:12px;",
            logo: null,
            mobileLogo: null
        }
    }, a[624] = {
        link: {
            linkIcon: "https://c.evidon.com/pub/icong1.png",
            linkStyle: "cursor:pointer;text-decoration:none;font-size:10pt;color:#000000;",
            mobileLinkIcon: "https://c.evidon.com/pub/icong1.png",
            mobileLinkStyle: "cursor:pointer;text-decoration:none;font-size:10pt;color:#000000;",
            mobileShowIcon: true,
            showIcon: true
        },
        button: {
            buttonIcon: "https://c.evidon.com/pub/icong2.png",
            buttonStyle: "position:fixed;padding:0 10px;border:1px solid #d7d7d7;cursor:pointer;line-height:36px;text-decoration:none;background:linear-gradient(to bottom, #e3e3e3, #c4c4c4);font-size:10pt;color:#000000;z-index:2147483600;bottom:0;left:0;",
            mobileButtonIcon: "https://c.evidon.com/pub/icong2.png",
            mobileButtonStyle: "position:fixed;padding:0 10px;border:1px solid #d7d7d7;cursor:pointer;line-height:36px;text-decoration:none;background:linear-gradient(to bottom, #e3e3e3, #c4c4c4);font-size:10pt;color:#000000;z-index:2147483600;bottom:0;left:0;",
            mobileShowIcon: true,
            mobileShowText: true,
            showIcon: true,
            showText: true
        },
        banner: {
            bannerStyle: "position:fixed;display:block;width:100%;background:#000000;font-size:14px;color:#000000;bottom:0;z-index:2147000001;border:0px solid #ffffff;",
            titleStyle: "display:block;font-size:18px;text-align:center;margin:8px 18px;",
            messageStyle: "display:inline-block;margin:12px 18px auto;font-family:Arial, sans-serif;font-weight:300;color:#ffffff;font-size:14px;line-height:1.5;padding:6px 0px 12px;",
            showAcceptButton: true,
            acceptButtonStyle: "display:block;float:right;margin:16px 24px;border:0px;background:#ffffff;color:#000000;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;",
            showCloseIcon: false,
            closeIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:2;",
            closeIconStroke: "#000000",
            closeIconThickness: "2",
            showIcon: false,
            iconStyle: "position:absolute;top:4px;left:4px;width:24px;height:24px;",
            showOptionButton: true,
            optionButtonStyle: "display:block;float:left;margin:16px 24px;border:0px;background:#ffffff;color:#000000;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;",
            showTitle: false,
            showDeclineButton: false,
            declineButtonStyle: "display:inline;border:0;background:#000000;color:#ffffff;padding:8px 22px;cursor:pointer;border-radius:4px;",
            backgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#000000;opacity:.75;",
            showBackground: false,
            mobileBannerStyle: "position:fixed;display:block;width:100%;background:#000000;font-size:14px;color:#000000;bottom:0;z-index:2147000001;",
            mobileTitleStyle: "display:block;font-size:18px;text-align:center;margin:8px 12px;",
            mobileMessageStyle: "display:inline-block;width:80%;margin:12px 18px auto;font-family:Arial, sans-serif;font-weight:300;color:#ffffff;font-size:14px;line-height:1.5;padding:6px 0px 12px;",
            mobileShowAcceptButton: true,
            mobileAcceptButtonStyle: "display:block;float:right;margin:16px 20px 16px 0;border:0px;background:#ffffff;color:#000000;padding:10px 25px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;",
            mobileShowCloseIcon: false,
            mobileCloseIconStyle: "position:absolute;top:4px;right:4px;height:12px;width:12px;stroke:#000000;stroke-width:2;",
            mobileCloseIconStroke: "#000000",
            mobileCloseIconThickness: "2",
            mobileShowIcon: false,
            mobileIconStyle: "position:absolute;top:4px;left:4px;width:16px;height:16px;",
            mobileShowCollapseMessage: false,
            mobileCollapseMessageStyle: "display:block;font-size:16px;text-align:center;padding:12px;cursor:pointer;",
            mobileShowOptionButton: true,
            mobileOptionButtonStyle: "display:block;float:left;margin:16px 0px 16px 20px;border:0px;background:#ffffff;color:#000000;padding:10px 25px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;",
            mobileShowTitle: false,
            mobileShowDeclineButton: false,
            mobileDeclineButtonStyle: "display:block;margin:auto;border:0;background:#000000;color:#ffffff;padding:6px 12px;cursor:pointer;",
            mobileBackgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#dddddd;opacity:.5;",
            mobileShowBackground: false,
            bannerIcon: null,
            mobileBannerIcon: null
        },
        barrier: {
            bannerStyle: "position:relative;display:block;margin:40px auto;background:#ffffff;width:60%;padding:12px;",
            titleStyle: "display:block;text-align:center;font-size:1.5rem;padding:4px 0;",
            messageStyle: "display:block;font-size:1rem;vertical-align:top;padding:16px 8px;line-height:1.4;",
            showCloseIcon: false,
            closeIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:2;",
            closeIconStroke: "#000000",
            closeIconThickness: "2",
            acceptButtonStyle: "display:block;margin:12px auto;padding:6px 8px;border:1px solid black;background:#111111;color:white;font-size:1.1rem;",
            acceptMessageStyle: "display:block;margin:14px 0 8px 0;font-size:1rem;padding:0 12px;line-height:1.5;",
            cookieButtonStyle: "display:block;border:0;background:transparent;font-size:1.1rem;margin:0 2px;text-decoration:underline;",
            cookieMessageStyle: "display:block;font-size:1rem;padding:12px 8px;line-height:1.4;",
            logoStyle: "display:block;width:100px;height:60px;margin:8px auto;",
            showCookieButtonIcon: true,
            showDeclineButton: false,
            declineButtonStyle: "display:block;margin:12px auto;padding:6px 8px;border:1px solid black;background:#111111;color:white;font-size:1.1rem;",
            mobileBannerStyle: "position:relative;display:block;margin:20px auto;background:#ffffff;width:100%;padding:12px;",
            mobileTitleStyle: "display:block;text-align:center;font-size:18px;padding:4px 0;",
            mobileMessageStyle: "display:block;font-size:12px;vertical-align:top;padding:16px 8px;line-height:1.4;",
            mobileShowCloseIcon: false,
            mobileCloseIconStyle: "position:absolute;top:4px;right:4px;height:12px;width:12px;stroke:#000000;stroke-width:2;",
            mobileCloseIconStroke: "#000000",
            mobileCloseIconThickness: "2",
            mobileAcceptButtonStyle: "display:block;margin:12px auto;padding:12px;border:1px solid black;background:#111111;color:white;font-size:16px;",
            mobileAcceptMessageStyle: "display:block;margin:14px 0 8px 0;font-size:12px;padding:0 12px;line-height:1.4;",
            mobileCookieButtonStyle: "display:block;border:0;background:transparent;font-size:14px;margin:0 2px;text-decoration:underline;",
            mobileCookieMessageStyle: "display:block;font-size:12px;padding:12px 8px;line-height:1.4;",
            mobileLogoStyle: "display:block;width:100px;margin:8px auto;",
            mobileShowCookieButtonIcon: false,
            mobileShowOptionButton: "null",
            mobileShowDeclineButton: false,
            mobileDeclineButtonStyle: "display:block;margin:12px auto;padding:12px;border:1px solid black;background:#111111;color:white;font-size:16px;",
            backgroundStyle: "background:#000000;opacity:.8;",
            backgroundStyle: "background:#000000;opacity:.8;",
            logo: null,
            mobileLogo: null,
            cookieButtonIcon: null,
            mobileCookieButtonIcon: null
        },
        l2: {
            overlayStyle: "display:block;position:absolute;top:10%;left:15%;width:70%;padding:18px;background:#ffffff;",
            titleStyle: "display:block;text-align:center;margin:6px auto;font-size:16px;font-weight:600;",
            showTitle: true,
            messageStyle: "display:block;margin:4px auto;font-size:12px;line-height:16px;",
            subtitleStyle: "display:block;font-size:14px;font-weight:500;margin:6px 0;",
            closeIconStyle: "display:block;position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#aaaaaa;stroke-width:2;cursor:pointer;",
            logoStyle: "display:block;margin:8px auto;width:150px;height:40px;background:#cccccc;color:white;border:1px solid #333333;",
            linkStyle: "display:block;color:#00AEF0;text-decoration:none;font-size:12px;font-weight:600;text-align:center;margin:18px 0;",
            backgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#dddddd;",
            showBackground: true,
            categoryHeaderStyle: "color:black;font-size:12px;",
            categoryDescriptionStyle: "color:#333333;font-size:12px;",
            showDeclineButton: true,
            showGlobalPrefButton: true,
            primaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#f2f2f2;background:#205493;cursor:pointer;border:2px solid transparent;float:right;",
            secondaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#333333;background:#f3f3f3;cursor:pointer;border:2px solid transparent;float:right;",
            tertiaryButtonStyle: "margin:2px auto;padding:4px 8px;color:#333333;cursor:pointer;border:2px solid transparent;font-size:11px;",
            backButtonStyle: "color:#00AEF0;text-decoration:none;font-size:12px;",
            mobileOverlayStyle: "display:block;position:absolute;top:1%;width:100%;padding:18px;background:#ffffff;",
            mobileTitleStyle: "display:block;text-align:center;margin:6px auto;font-size:16px;font-weight:600;",
            mobileShowTitle: true,
            mobileMessageStyle: "display:block;margin:4px auto;font-size:12px;line-height:16px;",
            mobileSubtitleStyle: "display:block;font-size:14px;font-weight:500;margin:6px 0;",
            mobileCloseIconStyle: "display:block;position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#aaaaaa;stroke-width:2;cursor:pointer;",
            mobileLogoStyle: "display:block;margin:8px auto;width:150px;height:40px;background:#cccccc;color:white;border:1px solid #333333;",
            mobileLinkStyle: "display:block;color:#00AEF0;text-decoration:none;font-size:12px;font-weight:600;text-align:center;margin:18px 0;",
            mobileBackgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#dddddd;",
            mobileShowBackground: true,
            mobileCategoryHeaderStyle: "color:black;font-size:12px;",
            mobileCategoryDescriptionStyle: "color:#333333;font-size:12px;",
            mobileShowDeclineButton: true,
            mobileShowGlobalPrefButton: true,
            mobilePrimaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#f2f2f2;background:#205493;cursor:pointer;border:2px solid transparent;float:right;",
            mobileSecondaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#333333;background:#f3f3f3;cursor:pointer;border:2px solid transparent;float:right;",
            mobileTertiaryButtonStyle: "margin:2px auto;padding:4px 8px;color:#333333;cursor:pointer;border:2px solid transparent;font-size:11px;",
            mobileBackButtonStyle: "color:#00AEF0;text-decoration:none;font-size:12px;",
            logo: null,
            mobileLogo: null
        }
    }, a[625] = {
        link: {
            linkIcon: "https://c.evidon.com/pub/icong1.png",
            linkStyle: "cursor:pointer;text-decoration:none;font-size:10pt;color:#000000;",
            mobileLinkIcon: "https://c.evidon.com/pub/icong1.png",
            mobileLinkStyle: "cursor:pointer;text-decoration:none;font-size:10pt;color:#000000;",
            mobileShowIcon: true,
            showIcon: true
        },
        button: {
            buttonIcon: "https://c.evidon.com/pub/icong2.png",
            buttonStyle: "position:fixed;padding:0 10px;border:1px solid #d7d7d7;cursor:pointer;line-height:36px;text-decoration:none;background:linear-gradient(to bottom, #e3e3e3, #c4c4c4);font-size:10pt;color:#000000;z-index:2147483600;bottom:0;left:0;",
            mobileButtonIcon: "https://c.evidon.com/pub/icong2.png",
            mobileButtonStyle: "position:fixed;padding:0 10px;border:1px solid #d7d7d7;cursor:pointer;line-height:36px;text-decoration:none;background:linear-gradient(to bottom, #e3e3e3, #c4c4c4);font-size:10pt;color:#000000;z-index:2147483600;bottom:0;left:0;",
            mobileShowIcon: true,
            mobileShowText: true,
            showIcon: true,
            showText: true
        },
        banner: {
            bannerStyle: "position:fixed;display:block;width:100%;background:#000000;font-size:14px;color:#000000;bottom:0;z-index:2147000001;border:0px solid #ffffff;",
            titleStyle: "display:none;font-size:18px;text-align:left;margin:8px 18px;",
            messageStyle: "display:inline-block;margin:12px 18px auto;font-family:Arial, sans-serif;font-weight:300;color:#ffffff;font-size:14px;line-height:1.5;padding:6px 0px 12px;",
            showAcceptButton: true,
            acceptButtonStyle: "display:block;float:right;margin:16px 24px;border:0px;background:#ffffff;color:#000000!important;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;text-shadow:none;height:auto;",
            showCloseIcon: false,
            closeIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:2;",
            closeIconStroke: "#000000",
            closeIconThickness: "2",
            showIcon: false,
            iconStyle: "position:absolute;top:4px;left:4px;width:24px;height:24px;",
            showOptionButton: true,
            optionButtonStyle: "display:block;float:left;margin:16px 24px;border:0px;background:#ffffff;color:#000000!important;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;text-shadow:none;height:auto;",
            showTitle: false,
            showDeclineButton: false,
            declineButtonStyle: "display:inline;border:0;background:#000000;color:#ffffff;padding:8px 22px;cursor:pointer;border-radius:4px;",
            backgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#000000;opacity:.5;",
            showBackground: false,
            mobileBannerStyle: "position:fixed;display:block;width:100%;background:#000000;font-size:14px;color:#000000;bottom:0;z-index:2147000001;border:0px solid #ffffff;",
            mobileTitleStyle: "display:none;font-size:18px;text-align:left;margin:8px 18px;",
            mobileMessageStyle: "display:inline-block;margin:12px 18px auto;font-family:Arial, sans-serif;font-weight:300;color:#ffffff;font-size:14px;line-height:1.5;padding:6px 0px 12px;",
            mobileShowAcceptButton: true,
            mobileAcceptButtonStyle: "display:block;float:right;margin:16px 20px 16px 0px;border:0px;background:#ffffff;color:#000000;padding:10px 25px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;",
            mobileShowCloseIcon: false,
            mobileCloseIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:2;",
            mobileCloseIconStroke: "#000000",
            mobileCloseIconThickness: "2",
            mobileShowIcon: false,
            mobileIconStyle: "position:absolute;top:4px;left:4px;width:24px;height:24px;",
            mobileShowCollapseMessage: false,
            mobileCollapseMessageStyle: "display:block;font-size:16px;text-align:center;padding:12px;cursor:pointer;",
            mobileShowOptionButton: true,
            mobileOptionButtonStyle: "display:block;float:left;margin:16px 0px 16px 20px;border:0px;background:#ffffff;color:#000000;padding:10px 25px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;",
            mobileShowTitle: false,
            mobileShowDeclineButton: false,
            mobileDeclineButtonStyle: "display:block;margin:auto;border:0;background:#000000;color:#ffffff;padding:6px 12px;cursor:pointer;",
            mobileBackgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#000000;opacity:.5;",
            mobileShowBackground: false,
            bannerIcon: null,
            mobileBannerIcon: null
        },
        barrier: {
            bannerStyle: "position:relative;display:block;margin:40px auto;background:#ffffff;width:60%;padding:12px;",
            titleStyle: "display:block;text-align:center;font-size:1.5rem;padding:4px 0;",
            messageStyle: "display:block;font-size:1rem;vertical-align:top;padding:16px 8px;line-height:1.4;",
            showCloseIcon: false,
            closeIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:2;",
            closeIconStroke: "#000000",
            closeIconThickness: "2",
            acceptButtonStyle: "display:block;margin:12px auto;padding:4px 6px;border:0px solid #000000;background:#000000;color:#ffffff;font-size:13px;border-radius:25px;",
            acceptMessageStyle: "display:block;margin:14px 0 8px 0;font-size:1rem;padding:0 12px;line-height:1.5;",
            cookieButtonStyle: "display:block;border:0;background:transparent;font-size:1.1rem;margin:0 2px;text-decoration:underline;",
            cookieMessageStyle: "display:block;font-size:1rem;padding:12px 8px;line-height:1.4;",
            logoStyle: "display:block;width:100px;height:60px;margin:8px auto;",
            showCookieButtonIcon: true,
            showDeclineButton: false,
            declineButtonStyle: "display:block;margin:12px auto;padding:6px 8px;border:1px solid black;background:#111111;color:white;font-size:1.1rem;",
            mobileBannerStyle: "position:relative;display:block;margin:20px auto;background:#ffffff;width:100%;padding:12px;",
            mobileTitleStyle: "display:block;text-align:center;font-size:18px;padding:4px 0;",
            mobileMessageStyle: "display:block;font-size:12px;vertical-align:top;padding:16px 8px;line-height:1.4;",
            mobileShowCloseIcon: false,
            mobileCloseIconStyle: "position:absolute;top:4px;right:4px;height:12px;width:12px;stroke:#000000;stroke-width:2;",
            mobileCloseIconStroke: "#000000",
            mobileCloseIconThickness: "2",
            mobileAcceptButtonStyle: "display:block;margin:12px auto;padding:12px;border:1px solid black;background:#111111;color:white;font-size:16px;",
            mobileAcceptMessageStyle: "display:block;margin:14px 0 8px 0;font-size:12px;padding:0 12px;line-height:1.4;",
            mobileCookieButtonStyle: "display:block;border:0;background:transparent;font-size:14px;margin:0 2px;text-decoration:underline;",
            mobileCookieMessageStyle: "display:block;font-size:12px;padding:12px 8px;line-height:1.4;",
            mobileLogoStyle: "display:block;width:100px;margin:8px auto;",
            mobileShowCookieButtonIcon: false,
            mobileShowOptionButton: "null",
            mobileShowDeclineButton: false,
            mobileDeclineButtonStyle: "display:block;margin:12px auto;padding:12px;border:1px solid black;background:#111111;color:white;font-size:16px;",
            backgroundStyle: "background:#000000;opacity:.8;",
            backgroundStyle: "background:#000000;opacity:.8;",
            logo: null,
            mobileLogo: null,
            cookieButtonIcon: null,
            mobileCookieButtonIcon: null
        },
        l2: {
            overlayStyle: "display:block;position:absolute;top:10%;left:15%;width:70%;padding:18px;background:#ffffff;",
            titleStyle: "display:block;text-align:center;margin:6px auto;font-size:16px;font-weight:600;font-family:Arial, sans-serif;color:#000000;",
            showTitle: true,
            messageStyle: "display:block;margin:4px auto;font-size:14px;line-height:16px;color:#000000;font-family:Arial, sans-serif;",
            subtitleStyle: "display:block;font-size:16px;font-weight:600;margin:6px 0;font-family:Arial, sans-serif;color:#000000;",
            closeIconStyle: "display:block;position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#aaaaaa;stroke-width:2;cursor:pointer;",
            logoStyle: "display:block;margin:8px auto;width:150px;height:40px;background:#cccccc;color:white;border:1px solid #333333;",
            linkStyle: "display:block;color:#ff0000;text-decoration:none;font-size:14px;font-weight:600;text-align:center;margin:18px 0;font-family:Arial, sans-serif;",
            backgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#000000;opacity:.5;",
            showBackground: true,
            categoryHeaderStyle: "null",
            categoryDescriptionStyle: "null",
            showDeclineButton: null,
            showGlobalPrefButton: null,
            primaryButtonStyle: "null",
            secondaryButtonStyle: "null",
            tertiaryButtonStyle: "null",
            backButtonStyle: "null",
            mobileOverlayStyle: "display:block;position:absolute;top:1%;width:100%;padding:18px;background:#ffffff;",
            mobileTitleStyle: "display:block;text-align:center;margin:6px auto;font-size:16px;font-weight:600;",
            mobileShowTitle: true,
            mobileMessageStyle: "display:block;margin:4px auto;font-size:12px;line-height:16px;",
            mobileSubtitleStyle: "display:block;font-size:14px;font-weight:500;margin:6px 0;",
            mobileCloseIconStyle: "display:block;position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#aaaaaa;stroke-width:2;cursor:pointer;",
            mobileLogoStyle: "display:block;margin:8px auto;width:150px;height:40px;background:#cccccc;color:white;border:1px solid #333333;",
            mobileLinkStyle: "display:block;color:#00AEF0;text-decoration:none;font-size:12px;font-weight:600;text-align:center;margin:18px 0;",
            mobileBackgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#dddddd;",
            mobileShowBackground: true,
            mobileCategoryHeaderStyle: "null",
            mobileCategoryDescriptionStyle: "null",
            mobileShowDeclineButton: null,
            mobileShowGlobalPrefButton: null,
            mobilePrimaryButtonStyle: "null",
            mobileSecondaryButtonStyle: "null",
            mobileTertiaryButtonStyle: "null",
            mobileBackButtonStyle: "null",
            logo: null,
            mobileLogo: null
        }
    }, a[678] = {
        link: {
            linkIcon: "https://c.evidon.com/pub/icong1.png",
            linkStyle: "cursor:pointer;text-decoration:none;font-size:10pt;color:#000101;",
            mobileLinkIcon: "https://c.evidon.com/pub/icong1.png",
            mobileLinkStyle: "cursor:pointer;text-decoration:none;font-size:10pt;color:#000101;",
            mobileShowIcon: true,
            showIcon: true
        },
        button: {
            buttonIcon: "https://c.evidon.com/pub/icong2.png",
            buttonStyle: "position:fixed;padding:0 10px;border:1px solid #000101;cursor:pointer;line-height:36px;text-decoration:none;background:#ffffff;font-size:10pt;color:#000101;z-index:2147483600;bottom:0;left:0;",
            mobileButtonIcon: "https://c.evidon.com/pub/icong2.png",
            mobileButtonStyle: "position:fixed;padding:0 10px;border:1px solid #000101;cursor:pointer;line-height:36px;text-decoration:none;background:#ffffff;font-size:10pt;color:#000101;z-index:2147483600;bottom:0;left:0;",
            mobileShowIcon: true,
            mobileShowText: true,
            showIcon: true,
            showText: true
        },
        banner: {
            bannerStyle: "position:fixed;display:block;width:100%;background:#ffffff;font-size:14px;color:#000000;bottom:0;z-index:2147000001;border:1px solid #000101;",
            titleStyle: "display:none;font-size:18px;text-align:left;margin:8px 18px;",
            messageStyle: "display:inline-block;margin:12px 18px auto;font-family:Arial, sans-serif;font-weight:300;color:#000101;font-size:13px;line-height:1.5;padding:6px 0px 12px;",
            showAcceptButton: true,
            acceptButtonStyle: "display:block;float:right;margin:16px 24px;border:0px;background:#000101;color:#ffffff!important;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;text-shadow:none;height:auto;",
            showCloseIcon: false,
            closeIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:2;",
            closeIconStroke: "#000000",
            closeIconThickness: "2",
            showIcon: false,
            iconStyle: "position:absolute;top:4px;left:4px;width:24px;height:24px;",
            showOptionButton: true,
            optionButtonStyle: "display:block;float:left;margin:16px 24px;border:0px;background:#000101;color:#ffffff!important;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;text-shadow:none;height:auto;",
            showTitle: false,
            showDeclineButton: false,
            declineButtonStyle: "display:inline;border:0;background:#000000;color:#ffffff;padding:8px 22px;cursor:pointer;border-radius:4px;",
            backgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#000000;opacity:.5;",
            showBackground: false,
            mobileBannerStyle: "position:fixed;display:block;width:100%;background:#ffffff;font-size:14px;color:#000000;bottom:0;z-index:2147000001;border:1px solid #000101;",
            mobileTitleStyle: "display:none;font-size:18px;text-align:left;margin:8px 18px;",
            mobileMessageStyle: "display:inline-block;margin:12px 18px auto;font-family:Arial, sans-serif;font-weight:300;color:#000101;font-size:13px;line-height:1.5;padding:6px 0px 12px;",
            mobileShowAcceptButton: true,
            mobileAcceptButtonStyle: "display:block;float:right;margin:16px 0px 16px 20px;border:0px;background:#000101;color:#ffffff;padding:10px 25px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;",
            mobileShowCloseIcon: false,
            mobileCloseIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:2;",
            mobileCloseIconStroke: "#000000",
            mobileCloseIconThickness: "2",
            mobileShowIcon: false,
            mobileIconStyle: "position:absolute;top:4px;left:4px;width:24px;height:24px;",
            mobileShowCollapseMessage: false,
            mobileCollapseMessageStyle: "display:block;font-size:16px;text-align:center;padding:12px;cursor:pointer;",
            mobileShowOptionButton: true,
            mobileOptionButtonStyle: "display:block;float:left;margin:16px 0px 16px 20px;border:0px;background:#000101;color:#ffffff;padding:10px 25px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;",
            mobileShowTitle: false,
            mobileShowDeclineButton: false,
            mobileDeclineButtonStyle: "display:inline;border:0;background:#000000;color:#ffffff;padding:8px 22px;cursor:pointer;border-radius:4px;",
            mobileBackgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#000000;opacity:.5;",
            mobileShowBackground: false,
            bannerIcon: null,
            mobileBannerIcon: null
        },
        barrier: {
            bannerStyle: "position:relative;display:block;margin:40px auto;background:#ffffff;width:60%;padding:12px;",
            titleStyle: "display:block;text-align:center;font-size:1.5rem;padding:4px 0;",
            messageStyle: "display:block;font-size:1rem;vertical-align:top;padding:16px 8px;line-height:1.4;",
            showCloseIcon: false,
            closeIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:2;",
            closeIconStroke: "#000000",
            closeIconThickness: "2",
            acceptButtonStyle: "display:block;margin:12px auto;padding:4px 6px;border:0px solid #000000;background:#000000;color:#ffffff;font-size:13px;border-radius:25px;",
            acceptMessageStyle: "display:block;margin:14px 0 8px 0;font-size:1rem;padding:0 12px;line-height:1.5;",
            cookieButtonStyle: "display:block;border:0;background:transparent;font-size:1.1rem;margin:0 2px;text-decoration:underline;",
            cookieMessageStyle: "display:block;font-size:1rem;padding:12px 8px;line-height:1.4;",
            logoStyle: "display:block;width:100px;height:60px;margin:8px auto;",
            showCookieButtonIcon: true,
            showDeclineButton: false,
            declineButtonStyle: "display:block;margin:12px auto;padding:6px 8px;border:1px solid black;background:#111111;color:white;font-size:1.1rem;",
            mobileBannerStyle: "position:relative;display:block;margin:20px auto;background:#ffffff;width:100%;padding:12px;",
            mobileTitleStyle: "display:block;text-align:center;font-size:18px;padding:4px 0;",
            mobileMessageStyle: "display:block;font-size:12px;vertical-align:top;padding:16px 8px;line-height:1.4;",
            mobileShowCloseIcon: false,
            mobileCloseIconStyle: "position:absolute;top:4px;right:4px;height:12px;width:12px;stroke:#000000;stroke-width:2;",
            mobileCloseIconStroke: "#000000",
            mobileCloseIconThickness: "2",
            mobileAcceptButtonStyle: "display:block;margin:12px auto;padding:12px;border:1px solid black;background:#111111;color:white;font-size:16px;",
            mobileAcceptMessageStyle: "display:block;margin:14px 0 8px 0;font-size:12px;padding:0 12px;line-height:1.4;",
            mobileCookieButtonStyle: "display:block;border:0;background:transparent;font-size:14px;margin:0 2px;text-decoration:underline;",
            mobileCookieMessageStyle: "display:block;font-size:12px;padding:12px 8px;line-height:1.4;",
            mobileLogoStyle: "display:block;width:100px;margin:8px auto;",
            mobileShowCookieButtonIcon: false,
            mobileShowOptionButton: "null",
            mobileShowDeclineButton: false,
            mobileDeclineButtonStyle: "display:block;margin:12px auto;padding:12px;border:1px solid black;background:#111111;color:white;font-size:16px;",
            backgroundStyle: "background:#000000;opacity:.8;",
            backgroundStyle: "background:#000000;opacity:.8;",
            logo: null,
            mobileLogo: null,
            cookieButtonIcon: null,
            mobileCookieButtonIcon: null
        },
        l2: {
            overlayStyle: "display:block;position:absolute;top:10%;left:15%;width:70%;padding:18px;background:#ffffff;",
            titleStyle: "display:block;text-align:center;margin:6px auto;font-size:16px;font-weight:600;",
            showTitle: true,
            messageStyle: "display:block;margin:4px auto;font-size:12px;line-height:16px;",
            subtitleStyle: "display:block;font-size:14px;font-weight:500;margin:6px 0;",
            closeIconStyle: "display:block;position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#aaaaaa;stroke-width:2;cursor:pointer;",
            logoStyle: "display:block;margin:8px auto;width:150px;height:40px;background:#cccccc;color:white;border:1px solid #333333;",
            linkStyle: "display:block;color:#00AEF0;text-decoration:none;font-size:12px;font-weight:600;text-align:center;margin:18px 0;",
            backgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#dddddd;",
            showBackground: true,
            categoryHeaderStyle: "color:black;font-size:12px;",
            categoryDescriptionStyle: "color:#333333;font-size:12px;",
            showDeclineButton: true,
            showGlobalPrefButton: true,
            primaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#f2f2f2;background:#205493;cursor:pointer;border:2px solid transparent;float:right;",
            secondaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#333333;background:#f3f3f3;cursor:pointer;border:2px solid transparent;float:right;",
            tertiaryButtonStyle: "margin:2px auto;padding:4px 8px;color:#333333;cursor:pointer;border:2px solid transparent;font-size:11px;",
            backButtonStyle: "color:#00AEF0;text-decoration:none;font-size:12px;",
            mobileOverlayStyle: "display:block;position:absolute;top:1%;width:100%;padding:18px;background:#ffffff;",
            mobileTitleStyle: "display:block;text-align:center;margin:6px auto;font-size:16px;font-weight:600;",
            mobileShowTitle: true,
            mobileMessageStyle: "display:block;margin:4px auto;font-size:12px;line-height:16px;",
            mobileSubtitleStyle: "display:block;font-size:14px;font-weight:500;margin:6px 0;",
            mobileCloseIconStyle: "display:block;position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#aaaaaa;stroke-width:2;cursor:pointer;",
            mobileLogoStyle: "display:block;margin:8px auto;width:150px;height:40px;background:#cccccc;color:white;border:1px solid #333333;",
            mobileLinkStyle: "display:block;color:#00AEF0;text-decoration:none;font-size:12px;font-weight:600;text-align:center;margin:18px 0;",
            mobileBackgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#dddddd;",
            mobileShowBackground: true,
            mobileCategoryHeaderStyle: "color:black;font-size:12px;",
            mobileCategoryDescriptionStyle: "color:#333333;font-size:12px;",
            mobileShowDeclineButton: true,
            mobileShowGlobalPrefButton: true,
            mobilePrimaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#f2f2f2;background:#205493;cursor:pointer;border:2px solid transparent;float:right;",
            mobileSecondaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#333333;background:#f3f3f3;cursor:pointer;border:2px solid transparent;float:right;",
            mobileTertiaryButtonStyle: "margin:2px auto;padding:4px 8px;color:#333333;cursor:pointer;border:2px solid transparent;font-size:11px;",
            mobileBackButtonStyle: "color:#00AEF0;text-decoration:none;font-size:12px;",
            logo: null,
            mobileLogo: null
        }
    }, a[682] = {
        link: {
            linkIcon: "https://c.evidon.com/pub/icong1.png",
            linkStyle: "cursor:pointer;text-decoration:none;font-size:10pt;color:#000000;",
            mobileLinkIcon: "https://c.evidon.com/pub/icong1.png",
            mobileLinkStyle: "cursor:pointer;text-decoration:none;font-size:10pt;color:#000000;",
            mobileShowIcon: true,
            showIcon: true
        },
        button: {
            buttonIcon: "https://c.evidon.com/pub/icong2.png",
            buttonStyle: "position:fixed;padding:0 10px;border:1px solid #d7d7d7;cursor:pointer;line-height:36px;text-decoration:none;background:linear-gradient(to bottom, #e3e3e3, #c4c4c4);font-size:10pt;color:#000000;z-index:2147483600;bottom:0;left:0;",
            mobileButtonIcon: "https://c.evidon.com/pub/icong2.png",
            mobileButtonStyle: "position:fixed;padding:0 10px;border:1px solid #d7d7d7;cursor:pointer;line-height:36px;text-decoration:none;background:linear-gradient(to bottom, #e3e3e3, #c4c4c4);font-size:10pt;color:#000000;z-index:2147483600;bottom:0;left:0;",
            mobileShowIcon: true,
            mobileShowText: true,
            showIcon: true,
            showText: true
        },
        banner: {
            bannerStyle: "position:fixed;display:block;width:100%;background:#000000;font-size:14px;color:#000000;bottom:0;z-index:2147000001;border:0px solid #ffffff;",
            titleStyle: "display:none;font-size:18px;text-align:left;margin:8px 18px;",
            messageStyle: "display:inline-block;margin:12px 18px auto;font-family:Arial, sans-serif;font-weight:300;color:#ffffff;font-size:14px;line-height:1.5;padding:6px 0px 12px;",
            showAcceptButton: true,
            acceptButtonStyle: "display:block;float:right;margin:16px 24px;border:0px;background:#ffffff;color:#000000;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;",
            showCloseIcon: false,
            closeIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:2;",
            closeIconStroke: "#000000",
            closeIconThickness: "2",
            showIcon: false,
            iconStyle: "position:absolute;top:4px;left:4px;width:24px;height:24px;",
            showOptionButton: true,
            optionButtonStyle: "display:block;float:left;margin:16px 24px;border:0px;background:#ffffff;color:#000000;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;",
            showTitle: false,
            showDeclineButton: false,
            declineButtonStyle: "display:inline;border:0;background:#000000;color:#ffffff;padding:8px 22px;cursor:pointer;border-radius:4px;",
            backgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#000000;opacity:.5;",
            showBackground: false,
            mobileBannerStyle: "position:fixed;display:block;width:100%;background:#000000;font-size:14px;color:#000000;bottom:0;z-index:2147000001;border:0px solid #ffffff;",
            mobileTitleStyle: "display:none;font-size:18px;text-align:left;margin:8px 18px;",
            mobileMessageStyle: "display:inline-block;margin:12px 18px auto;font-family:Arial, sans-serif;font-weight:300;color:#ffffff;font-size:14px;line-height:1.5;padding:6px 0px 12px;",
            mobileShowAcceptButton: true,
            mobileAcceptButtonStyle: "display:block;float:right;margin:16px 24px;border:0px;background:#ffffff;color:#000000;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;",
            mobileShowCloseIcon: false,
            mobileCloseIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:2;",
            mobileCloseIconStroke: "#000000",
            mobileCloseIconThickness: "2",
            mobileShowIcon: false,
            mobileIconStyle: "position:absolute;top:4px;left:4px;width:24px;height:24px;",
            mobileShowCollapseMessage: false,
            mobileCollapseMessageStyle: "display:block;font-size:16px;text-align:center;padding:12px;cursor:pointer;",
            mobileShowOptionButton: true,
            mobileOptionButtonStyle: "display:block;float:left;margin:16px 24px;border:0px;background:#ffffff;color:#000000;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;",
            mobileShowTitle: false,
            mobileShowDeclineButton: false,
            mobileDeclineButtonStyle: "display:block;margin:auto;border:0;background:#000000;color:#ffffff;padding:6px 12px;cursor:pointer;",
            mobileBackgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#000000;opacity:.5;",
            mobileShowBackground: false,
            bannerIcon: null,
            mobileBannerIcon: null
        },
        barrier: {
            bannerStyle: "position:relative;display:block;margin:40px auto;background:#ffffff;width:60%;padding:12px;",
            titleStyle: "display:block;text-align:center;font-size:1.5rem;padding:4px 0;",
            messageStyle: "display:block;font-size:1rem;vertical-align:top;padding:16px 8px;line-height:1.4;",
            showCloseIcon: false,
            closeIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:2;",
            closeIconStroke: "#000000",
            closeIconThickness: "2",
            acceptButtonStyle: "display:block;margin:12px auto;padding:4px 6px;border:0px solid #000000;background:#000000;color:#ffffff;font-size:13px;border-radius:25px;",
            acceptMessageStyle: "display:block;margin:14px 0 8px 0;font-size:1rem;padding:0 12px;line-height:1.5;",
            cookieButtonStyle: "display:block;border:0;background:transparent;font-size:1.1rem;margin:0 2px;text-decoration:underline;",
            cookieMessageStyle: "display:block;font-size:1rem;padding:12px 8px;line-height:1.4;",
            logoStyle: "display:block;width:100px;height:60px;margin:8px auto;",
            showCookieButtonIcon: true,
            showDeclineButton: false,
            declineButtonStyle: "display:block;margin:12px auto;padding:6px 8px;border:1px solid black;background:#111111;color:white;font-size:1.1rem;",
            mobileBannerStyle: "position:relative;display:block;margin:20px auto;background:#ffffff;width:100%;padding:12px;",
            mobileTitleStyle: "display:block;text-align:center;font-size:18px;padding:4px 0;",
            mobileMessageStyle: "display:block;font-size:12px;vertical-align:top;padding:16px 8px;line-height:1.4;",
            mobileShowCloseIcon: false,
            mobileCloseIconStyle: "position:absolute;top:4px;right:4px;height:12px;width:12px;stroke:#000000;stroke-width:2;",
            mobileCloseIconStroke: "#000000",
            mobileCloseIconThickness: "2",
            mobileAcceptButtonStyle: "display:block;margin:12px auto;padding:12px;border:1px solid black;background:#111111;color:white;font-size:16px;",
            mobileAcceptMessageStyle: "display:block;margin:14px 0 8px 0;font-size:12px;padding:0 12px;line-height:1.4;",
            mobileCookieButtonStyle: "display:block;border:0;background:transparent;font-size:14px;margin:0 2px;text-decoration:underline;",
            mobileCookieMessageStyle: "display:block;font-size:12px;padding:12px 8px;line-height:1.4;",
            mobileLogoStyle: "display:block;width:100px;margin:8px auto;",
            mobileShowCookieButtonIcon: false,
            mobileShowOptionButton: "null",
            mobileShowDeclineButton: false,
            mobileDeclineButtonStyle: "display:block;margin:12px auto;padding:12px;border:1px solid black;background:#111111;color:white;font-size:16px;",
            backgroundStyle: "background:#000000;opacity:.8;",
            backgroundStyle: "background:#000000;opacity:.8;",
            logo: null,
            mobileLogo: null,
            cookieButtonIcon: null,
            mobileCookieButtonIcon: null
        },
        l2: {
            overlayStyle: "display:block;position:absolute;top:10%;left:15%;width:70%;padding:18px;background:#ffffff;",
            titleStyle: "display:block;text-align:center;margin:6px auto;font-size:16px;font-weight:600;",
            showTitle: true,
            messageStyle: "display:block;margin:4px auto;font-size:12px;line-height:16px;",
            subtitleStyle: "display:block;font-size:14px;font-weight:500;margin:6px 0;",
            closeIconStyle: "display:block;position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#aaaaaa;stroke-width:2;cursor:pointer;",
            logoStyle: "display:block;margin:8px auto;width:150px;height:40px;background:#cccccc;color:white;border:1px solid #333333;",
            linkStyle: "display:block;color:#00AEF0;text-decoration:none;font-size:12px;font-weight:600;text-align:center;margin:18px 0;",
            backgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#dddddd;",
            showBackground: true,
            categoryHeaderStyle: "null",
            categoryDescriptionStyle: "null",
            showDeclineButton: null,
            showGlobalPrefButton: null,
            primaryButtonStyle: "null",
            secondaryButtonStyle: "null",
            tertiaryButtonStyle: "null",
            backButtonStyle: "null",
            mobileOverlayStyle: "display:block;position:absolute;top:1%;width:100%;padding:18px;background:#ffffff;",
            mobileTitleStyle: "display:block;text-align:center;margin:6px auto;font-size:16px;font-weight:600;",
            mobileShowTitle: true,
            mobileMessageStyle: "display:block;margin:4px auto;font-size:12px;line-height:16px;",
            mobileSubtitleStyle: "display:block;font-size:14px;font-weight:500;margin:6px 0;",
            mobileCloseIconStyle: "display:block;position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#aaaaaa;stroke-width:2;cursor:pointer;",
            mobileLogoStyle: "display:block;margin:8px auto;width:150px;height:40px;background:#cccccc;color:white;border:1px solid #333333;",
            mobileLinkStyle: "display:block;color:#00AEF0;text-decoration:none;font-size:12px;font-weight:600;text-align:center;margin:18px 0;",
            mobileBackgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#dddddd;",
            mobileShowBackground: true,
            mobileCategoryHeaderStyle: "null",
            mobileCategoryDescriptionStyle: "null",
            mobileShowDeclineButton: null,
            mobileShowGlobalPrefButton: null,
            mobilePrimaryButtonStyle: "null",
            mobileSecondaryButtonStyle: "null",
            mobileTertiaryButtonStyle: "null",
            mobileBackButtonStyle: "null",
            logo: null,
            mobileLogo: null
        }
    }, a[826] = {
        link: {
            linkIcon: "https://c.evidon.com/pub/icong1.png",
            linkStyle: "cursor:pointer;text-decoration:none;font-size:10pt;color:#000000;",
            mobileLinkIcon: "https://c.evidon.com/pub/icong1.png",
            mobileLinkStyle: "cursor:pointer;text-decoration:none;font-size:10pt;color:#000000;",
            mobileShowIcon: true,
            showIcon: true
        },
        button: {
            buttonIcon: "https://c.evidon.com/pub/icong2.png",
            buttonStyle: "position:fixed;padding:0 10px;border:1px solid #d7d7d7;cursor:pointer;line-height:36px;text-decoration:none;background:linear-gradient(to bottom, #e3e3e3, #c4c4c4);font-size:10pt;color:#000000;z-index:2147483600;bottom:0;left:0;",
            mobileButtonIcon: "https://c.evidon.com/pub/icong2.png",
            mobileButtonStyle: "position:fixed;padding:0 10px;border:1px solid #d7d7d7;cursor:pointer;line-height:36px;text-decoration:none;background:linear-gradient(to bottom, #e3e3e3, #c4c4c4);font-size:10pt;color:#000000;z-index:2147483600;bottom:0;left:0;",
            mobileShowIcon: true,
            mobileShowText: true,
            showIcon: true,
            showText: true
        },
        banner: {
            bannerStyle: "position:fixed;display:block;width:100%;background:#eeeeee;font-size:12px;color:#000000;bottom:0;z-index:2147000001;border:0px solid #000000;",
            titleStyle: "display:block;font-size:10px;text-align:center;margin:8px 18px;color:#444444;",
            messageStyle: "display:inline-block;margin:5px 80px 5px 5px;font-family:Arial, sans-serif;font-weight:300;color:#444444;font-size:12px;line-height:1.2;padding:10px;text-align:left;",
            showAcceptButton: true,
            acceptButtonStyle: "display:inline-block;float:right;margin:0 10px 0 0;border:0px;background:#29ace2;color:#ffffff;padding:10px;cursor:pointer;font-size:12px;font-weight:600;font-family:Arial, sans-serif;text-transform:uppercase;text-align:center;position:absolute;top:50%;transform:translateY(-50%);right:0;",
            showCloseIcon: false,
            closeIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:2;",
            closeIconStroke: "#000000",
            closeIconThickness: "2",
            showIcon: false,
            iconStyle: "position:absolute;top:4px;left:4px;width:24px;height:24px;",
            showOptionButton: false,
            optionButtonStyle: "display:inline;border:0;background:#000000;color:#ffffff;padding:8px 22px;cursor:pointer;border-radius:4px;",
            showTitle: false,
            showDeclineButton: false,
            declineButtonStyle: "display:block;float:left;margin:5px 5px 5px 5px;border:0px;background:#ffffff;color:#000000!important;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:12px;font-weight:600;font-family:Arial, sans-serif;text-shadow:none;height:auto;",
            backgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#000000;opacity:.5;",
            showBackground: false,
            mobileBannerStyle: "position:fixed;display:block;width:100%;background:#eeeeee;font-size:12px;color:#000000;bottom:0;z-index:2147000001;border:0px solid #000000;",
            mobileTitleStyle: "display:block;font-size:10px;text-align:center;margin:8px 18px;color:#444444;",
            mobileMessageStyle: "display:inline-block;margin:5px 80px 5px 5px;font-family:Arial, sans-serif;font-weight:300;color:#444444;font-size:12px;line-height:1.2;padding:10px;text-align:left;",
            mobileShowAcceptButton: true,
            mobileAcceptButtonStyle: "display:inline-block;float:right;margin:0 10px 0 0;border:0px;background:#29ace2;color:#ffffff;padding:10px;cursor:pointer;font-size:12px;font-weight:600;font-family:Arial, sans-serif;text-transform:uppercase;text-align:center;position:absolute;top:50%;transform:translateY(-50%);right:0;",
            mobileShowCloseIcon: false,
            mobileCloseIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:2;",
            mobileCloseIconStroke: "#000000",
            mobileCloseIconThickness: "2",
            mobileShowIcon: false,
            mobileIconStyle: "position:absolute;top:4px;left:4px;width:24px;height:24px;",
            mobileShowCollapseMessage: false,
            mobileCollapseMessageStyle: "display:block;font-size:16px;text-align:center;padding:12px;cursor:pointer;",
            mobileShowOptionButton: false,
            mobileOptionButtonStyle: "display:block;float:left;margin:16px 0px 16px 20px;border:0px;background:#ffffff;color:#000000;padding:10px 25px;cursor:pointer;border-radius:25px;font-size:12px;font-weight:600;font-family:Arial, sans-serif;",
            mobileShowTitle: false,
            mobileShowDeclineButton: false,
            mobileDeclineButtonStyle: "display:block;float:left;margin:5px 5px 5px 5px;border:0px;background:#ffffff;color:#000000!important;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:12px;font-weight:600;font-family:Arial, sans-serif;text-shadow:none;height:auto;",
            mobileBackgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#000000;opacity:.5;",
            mobileShowBackground: false,
            bannerIcon: null,
            mobileBannerIcon: null
        },
        barrier: {
            bannerStyle: "position:relative;display:block;margin:40px auto;background:#ffffff;width:60%;padding:12px;",
            titleStyle: "display:block;text-align:center;font-size:1.5rem;padding:4px 0;",
            messageStyle: "display:block;font-size:1rem;vertical-align:top;padding:16px 8px;line-height:1.4;",
            showCloseIcon: false,
            closeIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:2;",
            closeIconStroke: "#000000",
            closeIconThickness: "2",
            acceptButtonStyle: "display:block;margin:12px auto;padding:4px 6px;border:0px solid #000000;background:#000000;color:#ffffff;font-size:13px;border-radius:25px;",
            acceptMessageStyle: "display:block;margin:14px 0 8px 0;font-size:1rem;padding:0 12px;line-height:1.5;",
            cookieButtonStyle: "display:block;border:0;background:transparent;font-size:1.1rem;margin:0 2px;text-decoration:underline;",
            cookieMessageStyle: "display:block;font-size:1rem;padding:12px 8px;line-height:1.4;",
            logoStyle: "display:block;width:100px;height:60px;margin:8px auto;",
            showCookieButtonIcon: true,
            showDeclineButton: false,
            declineButtonStyle: "display:block;margin:12px auto;padding:6px 8px;border:1px solid black;background:#111111;color:white;font-size:1.1rem;",
            mobileBannerStyle: "position:relative;display:block;margin:20px auto;background:#ffffff;width:100%;padding:12px;",
            mobileTitleStyle: "display:block;text-align:center;font-size:18px;padding:4px 0;",
            mobileMessageStyle: "display:block;font-size:12px;vertical-align:top;padding:16px 8px;line-height:1.4;",
            mobileShowCloseIcon: false,
            mobileCloseIconStyle: "position:absolute;top:4px;right:4px;height:12px;width:12px;stroke:#000000;stroke-width:2;",
            mobileCloseIconStroke: "#000000",
            mobileCloseIconThickness: "2",
            mobileAcceptButtonStyle: "display:block;margin:12px auto;padding:12px;border:1px solid black;background:#111111;color:white;font-size:16px;",
            mobileAcceptMessageStyle: "display:block;margin:14px 0 8px 0;font-size:12px;padding:0 12px;line-height:1.4;",
            mobileCookieButtonStyle: "display:block;border:0;background:transparent;font-size:14px;margin:0 2px;text-decoration:underline;",
            mobileCookieMessageStyle: "display:block;font-size:12px;padding:12px 8px;line-height:1.4;",
            mobileLogoStyle: "display:block;width:100px;margin:8px auto;",
            mobileShowCookieButtonIcon: false,
            mobileShowOptionButton: "null",
            mobileShowDeclineButton: false,
            mobileDeclineButtonStyle: "display:block;margin:12px auto;padding:12px;border:1px solid black;background:#111111;color:white;font-size:16px;",
            backgroundStyle: "background:#000000;opacity:.8;",
            backgroundStyle: "background:#000000;opacity:.8;",
            logo: null,
            mobileLogo: null,
            cookieButtonIcon: null,
            mobileCookieButtonIcon: null
        },
        l2: {
            overlayStyle: "display:block;position:absolute;top:10%;left:15%;width:70%;padding:18px;background:#ffffff;",
            titleStyle: "display:block;text-align:center;margin:6px auto;font-size:16px;font-weight:600;font-family:Arial, sans-serif;color:#000000;",
            showTitle: true,
            messageStyle: "display:block;margin:4px auto;font-size:14px;line-height:16px;color:#000000;font-family:Arial, sans-serif;",
            subtitleStyle: "display:block;font-size:16px;font-weight:600;margin:6px 0;font-family:Arial, sans-serif;color:#000000;",
            closeIconStyle: "display:block;position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#aaaaaa;stroke-width:2;cursor:pointer;",
            logoStyle: "display:block;margin:8px auto;width:150px;height:40px;background:#cccccc;color:white;border:1px solid #333333;",
            linkStyle: "display:block;color:#ff0000;text-decoration:none;font-size:14px;font-weight:600;text-align:center;margin:18px 0;font-family:Arial, sans-serif;",
            backgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#000000;opacity:.5;",
            showBackground: true,
            categoryHeaderStyle: "color:black;font-size:12px;",
            categoryDescriptionStyle: "color:#333333;font-size:12px;",
            showDeclineButton: true,
            showGlobalPrefButton: true,
            primaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#f2f2f2;background:#205493;cursor:pointer;border:2px solid transparent;float:right;",
            secondaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#333333;background:#f3f3f3;cursor:pointer;border:2px solid transparent;float:right;",
            tertiaryButtonStyle: "margin:2px auto;padding:4px 8px;color:#333333;cursor:pointer;border:2px solid transparent;font-size:11px;",
            backButtonStyle: "color:#00AEF0;text-decoration:none;font-size:12px;",
            mobileOverlayStyle: "display:block;position:absolute;top:1%;width:100%;padding:18px;background:#ffffff;",
            mobileTitleStyle: "display:block;text-align:center;margin:6px auto;font-size:16px;font-weight:600;",
            mobileShowTitle: true,
            mobileMessageStyle: "display:block;margin:4px auto;font-size:12px;line-height:16px;",
            mobileSubtitleStyle: "display:block;font-size:14px;font-weight:500;margin:6px 0;",
            mobileCloseIconStyle: "display:block;position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#aaaaaa;stroke-width:2;cursor:pointer;",
            mobileLogoStyle: "display:block;margin:8px auto;width:150px;height:40px;background:#cccccc;color:white;border:1px solid #333333;",
            mobileLinkStyle: "display:block;color:#00AEF0;text-decoration:none;font-size:12px;font-weight:600;text-align:center;margin:18px 0;",
            mobileBackgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#dddddd;",
            mobileShowBackground: true,
            mobileCategoryHeaderStyle: "color:black;font-size:12px;",
            mobileCategoryDescriptionStyle: "color:#333333;font-size:12px;",
            mobileShowDeclineButton: true,
            mobileShowGlobalPrefButton: true,
            mobilePrimaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#f2f2f2;background:#205493;cursor:pointer;border:2px solid transparent;float:right;",
            mobileSecondaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#333333;background:#f3f3f3;cursor:pointer;border:2px solid transparent;float:right;",
            mobileTertiaryButtonStyle: "margin:2px auto;padding:4px 8px;color:#333333;cursor:pointer;border:2px solid transparent;font-size:11px;",
            mobileBackButtonStyle: "color:#00AEF0;text-decoration:none;font-size:12px;",
            logo: null,
            mobileLogo: null
        }
    }, a[1138] = {
        link: {
            linkIcon: "https://c.evidon.com/pub/icong1.png",
            linkStyle: "cursor:pointer;text-decoration:none;font-size:10pt;color:#000000;",
            mobileLinkIcon: "https://c.evidon.com/pub/icong1.png",
            mobileLinkStyle: "cursor:pointer;text-decoration:none;font-size:10pt;color:#000000;",
            mobileShowIcon: true,
            showIcon: true
        },
        button: {
            buttonIcon: "https://c.evidon.com/pub/icong2.png",
            buttonStyle: "position:fixed;padding:0 10px;border:1px solid #d7d7d7;cursor:pointer;line-height:36px;text-decoration:none;background:#060606;font-size:10pt;color:#e6e6e6;bottom:4px;left:4px;border-radius:8px;",
            mobileButtonIcon: "https://c.evidon.com/pub/icong2.png",
            mobileButtonStyle: "position:fixed;padding:0 10px;border:1px solid #d7d7d7;cursor:pointer;line-height:36px;text-decoration:none;background:#060606;font-size:10pt;color:#e6e6e6;bottom:4px;left:4px;border-radius:8px;",
            mobileShowIcon: true,
            mobileShowText: true,
            showIcon: true,
            showText: true
        },
        banner: {
            bannerStyle: "position:fixed;display:block;width:100%;background:#ffffff;font-size:14px;color:#000000;bottom:0;z-index:2147000001;border:1px solid #000101;",
            titleStyle: "display:none;font-size:18px;text-align:left;margin:8px 18px;",
            messageStyle: "display:inline-block;margin:12px 18px auto;font-family:Arial, sans-serif;font-weight:300;color:#000101;font-size:14px;line-height:1.5;padding:6px 0px 12px;",
            showAcceptButton: true,
            acceptButtonStyle: "display:block;float:right;margin:16px 24px;border:0px;background:#000101;color:#ffffff!important;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;text-shadow:none;height:auto;",
            showCloseIcon: false,
            closeIconStyle: "position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#e6e6e6;stroke-width:2;",
            closeIconStroke: "#e6e6e6",
            closeIconThickness: "2",
            showIcon: false,
            iconStyle: "position:absolute;top:4px;left:4px;width:24px;height:24px;",
            showOptionButton: true,
            optionButtonStyle: "display:block;float:left;margin:16px 24px;border:0px;background:#000101;color:#ffffff!important;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;text-shadow:none;height:auto;",
            showTitle: false,
            showDeclineButton: false,
            declineButtonStyle: "display:inline;border:0;background:#000000;color:#ffffff;padding:8px 22px;cursor:pointer;border-radius:4px;",
            backgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#dddddd;opacity:.5;",
            showBackground: false,
            mobileBannerStyle: "position:fixed;display:block;width:100%;background:#ffffff;font-size:14px;color:#000000;bottom:0;z-index:2147000001;border:1px solid #000101;",
            mobileTitleStyle: "display:none;font-size:18px;text-align:left;margin:8px 18px;",
            mobileMessageStyle: "display:inline-block;margin:12px 18px auto;font-family:Arial, sans-serif;font-weight:300;color:#000101;font-size:14px;line-height:1.5;padding:6px 0px 12px;",
            mobileShowAcceptButton: true,
            mobileAcceptButtonStyle: "display:block;float:right;margin:16px 24px;border:0px;background:#000101;color:#ffffff!important;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;text-shadow:none;height:auto;",
            mobileShowCloseIcon: false,
            mobileCloseIconStyle: "position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#e6e6e6;stroke-width:2;",
            mobileCloseIconStroke: "#e6e6e6",
            mobileCloseIconThickness: "2",
            mobileShowIcon: false,
            mobileIconStyle: "position:absolute;top:4px;left:4px;width:24px;height:24px;",
            mobileShowCollapseMessage: false,
            mobileCollapseMessageStyle: "display:block;font-size:16px;text-align:center;padding:12px;cursor:pointer;",
            mobileShowOptionButton: true,
            mobileOptionButtonStyle: "display:block;float:left;margin:16px 24px;border:0px;background:#000101;color:#ffffff!important;padding:10px 35px;cursor:pointer;border-radius:25px;font-size:14px;font-weight:600;font-family:Arial, sans-serif;text-shadow:none;height:auto;",
            mobileShowTitle: false,
            mobileShowDeclineButton: false,
            mobileDeclineButtonStyle: "display:inline;border:0;background:#000000;color:#ffffff;padding:8px 22px;cursor:pointer;border-radius:4px;",
            mobileBackgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#dddddd;opacity:.5;",
            mobileShowBackground: false,
            bannerIcon: null,
            mobileBannerIcon: null
        },
        barrier: {
            bannerStyle: "position:relative;display:block;margin:40px auto;background:#030303;width:60%;padding:12px;",
            titleStyle: "display:block;text-align:center;font-size:1.5rem;padding:4px 0;color:#e6e6e6;",
            messageStyle: "display:block;font-size:1rem;vertical-align:top;padding:16px 8px;line-height:1.4;color:#e6e6e6;",
            showCloseIcon: false,
            closeIconStyle: "position:absolute;top:4px;right:4px;height:16px;width:16px;stroke:#000000;stroke-width:0;",
            closeIconStroke: "#000000",
            closeIconThickness: "0",
            acceptButtonStyle: "display:block;margin:22px auto;padding:6px 18px;border:1px solid #565454;background:#393939;color:#ffffff;font-size:1.1rem;border-radius:8px;",
            acceptMessageStyle: "display:block;margin:14px 0 8px 0;font-size:1rem;padding:0 12px;line-height:1.5;color:#e6e6e6;",
            cookieButtonStyle: "display:block;border:0 solid #000000;background:transparent;font-size:1.1rem;margin:0 2px;text-decoration:underline;color:#e6e6e6;",
            cookieMessageStyle: "display:block;font-size:1rem;padding:12px 8px;line-height:1.4;color:#e6e6e6;",
            logoStyle: "display:block;width:;height:40px;margin:8px auto;",
            showCookieButtonIcon: true,
            showDeclineButton: false,
            declineButtonStyle: "display:block;margin:12px auto;padding:6px 8px;border:1px solid black;background:#111111;color:white;font-size:1.1rem;",
            mobileBannerStyle: "position:relative;display:block;margin:40px auto;background:#030303;width:100%;padding:12px;",
            mobileTitleStyle: "display:block;text-align:center;font-size:1.5rem;padding:4px 0;color:#e6e6e6;",
            mobileMessageStyle: "display:block;font-size:1rem;vertical-align:top;padding:16px 8px;line-height:1.4;color:#e6e6e6;",
            mobileShowCloseIcon: false,
            mobileCloseIconStyle: "position:absolute;top:4px;right:4px;height:12px;width:12px;stroke:#000000;stroke-width:0;",
            mobileCloseIconStroke: "#000000",
            mobileCloseIconThickness: "0",
            mobileAcceptButtonStyle: "display:block;margin:22px auto;padding:6px 18px;border:1px solid #565454;background:#393939;color:#ffffff;font-size:1.1rem;border-radius:8px;",
            mobileAcceptMessageStyle: "display:block;margin:14px 0 8px 0;font-size:1rem;padding:0 12px;line-height:1.5;color:#e6e6e6;",
            mobileCookieButtonStyle: "display:block;border:0 solid #000000;background:transparent;font-size:1.1rem;margin:0 2px;text-decoration:underline;color:#e6e6e6;",
            mobileCookieMessageStyle: "display:block;font-size:1rem;padding:12px 8px;line-height:1.4;color:#e6e6e6;",
            mobileLogoStyle: "display:block;width:;height:40px;margin:8px auto;",
            mobileShowCookieButtonIcon: false,
            mobileShowOptionButton: "null",
            mobileShowDeclineButton: false,
            mobileDeclineButtonStyle: "display:block;margin:12px auto;padding:12px;border:1px solid black;background:#111111;color:white;font-size:16px;",
            backgroundStyle: "background:#9a9a9a;opacity:.8;",
            backgroundStyle: "background:#9a9a9a;opacity:.8;",
            logo: null,
            mobileLogo: null,
            cookieButtonIcon: null,
            mobileCookieButtonIcon: null
        },
        l2: {
            overlayStyle: "display:block;position:absolute;top:10%;left:15%;width:70%;padding:18px;background:#2d2d2d;box-shadow:0 2px 12px rgba(0,0,0,.5);",
            titleStyle: "display:block;text-align:center;margin:6px auto;font-size:20px;font-weight:300;font-family:Open Sans;color:#f5f5f5;",
            showTitle: true,
            messageStyle: "display:block;margin:0px auto 6px;font-size:13px;line-height:16px;font-family:Open Sans;font-weight:300;color:#f5f5f5;",
            subtitleStyle: "display:block;font-size:14px;font-weight:600;margin:6px 0  0px;font-family:Open Sans;color:#f5f5f5;",
            closeIconStyle: "display:block;position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#f5f5f5;stroke-width:3;cursor:pointer;",
            logoStyle: "display:block;margin:8px auto;width:136px;height:45.33px;color:white;",
            linkStyle: "display:block;color:#3eccff;text-decoration:none;font-size:13px;font-weight:400;text-align:left;margin:10px 0;font-family:Open Sans;",
            backgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#fafafa;opacity:.6;",
            showBackground: true,
            categoryHeaderStyle: "color:black;font-size:12px;",
            categoryDescriptionStyle: "color:#333333;font-size:12px;",
            showDeclineButton: true,
            showGlobalPrefButton: true,
            primaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#f2f2f2;background:#205493;cursor:pointer;border:2px solid transparent;float:right;",
            secondaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#333333;background:#f3f3f3;cursor:pointer;border:2px solid transparent;float:right;",
            tertiaryButtonStyle: "margin:2px auto;padding:4px 8px;color:#333333;cursor:pointer;border:2px solid transparent;font-size:11px;",
            backButtonStyle: "color:#00AEF0;text-decoration:none;font-size:12px;",
            mobileOverlayStyle: "display:block;position:absolute;top:1%;padding:18px;background:#2d2d2d;width:100%;",
            mobileTitleStyle: "display:block;text-align:center;margin:6px auto;font-size:16px;font-weight:300;font-family:Open Sans;color:#f5f5f5;",
            mobileShowTitle: true,
            mobileMessageStyle: "display:block;margin:0px auto 6px;font-size:13px;line-height:16px;font-family:Open Sans;font-weight:300;color:#f5f5f5;",
            mobileSubtitleStyle: "display:block;font-size:14px;font-weight:700;margin:6px 0  0px;font-family:Open Sans;color:#f5f5f5;",
            mobileCloseIconStyle: "display:block;position:absolute;top:8px;right:8px;height:12px;width:12px;stroke:#f5f5f5;stroke-width:3;cursor:pointer;",
            mobileLogoStyle: "display:block;margin:8px auto;width:136px;height:45.333px;color:white;",
            mobileLinkStyle: "display:block;color:#3eccff;text-decoration:none;font-size:13px;font-weight:400;text-align:left;margin:10px 0;font-family:Open Sans;",
            mobileBackgroundStyle: "display:block;position:absolute;top:0;left:0;width:100%;height:100%;background:#fafafa;",
            mobileShowBackground: true,
            mobileCategoryHeaderStyle: "color:black;font-size:12px;",
            mobileCategoryDescriptionStyle: "color:#333333;font-size:12px;",
            mobileShowDeclineButton: true,
            mobileShowGlobalPrefButton: true,
            mobilePrimaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#f2f2f2;background:#205493;cursor:pointer;border:2px solid transparent;float:right;",
            mobileSecondaryButtonStyle: "display:inline-block;margin:4px;padding:8px 16px;color:#333333;background:#f3f3f3;cursor:pointer;border:2px solid transparent;float:right;",
            mobileTertiaryButtonStyle: "margin:2px auto;padding:4px 8px;color:#333333;cursor:pointer;border:2px solid transparent;font-size:11px;",
            mobileBackButtonStyle: "color:#00AEF0;text-decoration:none;font-size:12px;",
            logo: null,
            mobileLogo: null
        }
    };
    if (window.evidon && window.evidon.notice) {
        window.evidon.notice.setThemes(a)
    } else {
        if (!window.evidon) {
            window.evidon = {}
        }
        window.evidon.themes = a
    }
})();