// Copyright Google, Inc. All Rights Reserved.

(function() {
  var h=void 0,k=!0,l=null,m=!1,q,s=this;
function t(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function aa(a){var b=t(a);return"array"==b||"object"==b&&"number"==typeof a.length}function v(a){return"string"==typeof a}function ba(a){var b=typeof a;return"object"==b&&a!=l||"function"==b}function w(a){return a[ca]||(a[ca]=++da)}var ca="closure_uid_"+(1E9*Math.random()>>>0),da=0;function ea(a,b,c){return a.call.apply(a.bind,arguments)}
function fa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function x(a,b,c){x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:fa;return x.apply(l,arguments)}
function ga(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}var ha=Date.now||function(){return+new Date};function y(a,b){function c(){}c.prototype=b.prototype;a.e=b.prototype;a.prototype=new c}Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return x.apply(l,c)}return x(this,a)};function z(){0!=ia&&(this.Ra=Error().stack,ja[w(this)]=this)}var ia=0,ja={};z.prototype.ia=m;z.prototype.q=function(){if(!this.ia&&(this.ia=k,this.c(),0!=ia)){var a=w(this);delete ja[a]}};z.prototype.c=function(){if(this.F)for(;this.F.length;)this.F.shift()()};function ka(a){a&&"function"==typeof a.q&&a.q()};function la(a,b){for(var c=1;c<arguments.length;c++){var d=String(arguments[c]).replace(/\$/g,"$$$$");a=a.replace(/\%s/,d)}return a}function ma(a){if(!na.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(oa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(pa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(qa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ra,"&quot;"));return a}var oa=/&/g,pa=/</g,qa=/>/g,ra=/\"/g,na=/[&<>\"]/;
function sa(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})}function ta(a){var b=v(h)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,f){return b+f.toUpperCase()})};var A=Array.prototype,ua=A.indexOf?function(a,b,c){return A.indexOf.call(a,b,c)}:function(a,b,c){c=c==l?0:0>c?Math.max(0,a.length+c):c;if(v(a))return!v(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},va=A.forEach?function(a,b,c){A.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=v(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)},wa=A.filter?function(a,b,c){return A.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],e=0,g=v(a)?
a.split(""):a,n=0;n<d;n++)if(n in g){var p=g[n];b.call(c,p,n,a)&&(f[e++]=p)}return f};function xa(a,b){var c=ua(a,b);0<=c&&A.splice.call(a,c,1)}function ya(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function za(a,b,c){return 2>=arguments.length?A.slice.call(a,b):A.slice.call(a,b,c)};var B,Aa,Ba,Ca;function Da(){return s.navigator?s.navigator.userAgent:l}Ca=Ba=Aa=B=m;var Ea;if(Ea=Da()){var Fa=s.navigator;B=0==Ea.indexOf("Opera");Aa=!B&&-1!=Ea.indexOf("MSIE");Ba=!B&&-1!=Ea.indexOf("WebKit");Ca=!B&&!Ba&&"Gecko"==Fa.product}var Ga=B,C=Aa,E=Ca,F=Ba,Ha=s.navigator,Ia=-1!=(Ha&&Ha.platform||"").indexOf("Mac");function Ja(){var a=s.document;return a?a.documentMode:h}var Ka;
a:{var La="",G;if(Ga&&s.opera)var Ma=s.opera.version,La="function"==typeof Ma?Ma():Ma;else if(E?G=/rv\:([^\);]+)(\)|;)/:C?G=/MSIE\s+([^\);]+)(\)|;)/:F&&(G=/WebKit\/(\S+)/),G)var Na=G.exec(Da()),La=Na?Na[1]:"";if(C){var Oa=Ja();if(Oa>parseFloat(La)){Ka=String(Oa);break a}}Ka=La}var Pa={};
function H(a){var b;if(!(b=Pa[a])){b=0;for(var c=String(Ka).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var g=c[e]||"",n=d[e]||"",p=RegExp("(\\d*)(\\D*)","g"),T=RegExp("(\\d*)(\\D*)","g");do{var r=p.exec(g)||["","",""],u=T.exec(n)||["","",""];if(0==r[0].length&&0==u[0].length)break;b=((0==r[1].length?0:parseInt(r[1],10))<(0==u[1].length?0:parseInt(u[1],10))?-1:(0==r[1].length?0:parseInt(r[1],
10))>(0==u[1].length?0:parseInt(u[1],10))?1:0)||((0==r[2].length)<(0==u[2].length)?-1:(0==r[2].length)>(0==u[2].length)?1:0)||(r[2]<u[2]?-1:r[2]>u[2]?1:0)}while(0==b)}b=Pa[a]=0<=b}return b}var Qa=s.document,I=!Qa||!C?h:Ja()||("CSS1Compat"==Qa.compatMode?parseInt(Ka,10):5);var Ra=!C||C&&9<=I,Sa=C&&!H("9");!F||H("528");E&&H("1.9b")||C&&H("8")||Ga&&H("9.5")||F&&H("528");E&&!H("8")||C&&H("9");function J(a,b){this.type=a;this.currentTarget=this.target=b}q=J.prototype;q.c=function(){};q.q=function(){};q.w=m;q.defaultPrevented=m;q.S=k;q.preventDefault=function(){this.defaultPrevented=k;this.S=m};function Ta(a){Ta[" "](a);return a}Ta[" "]=function(){};function K(a,b){a&&this.O(a,b)}y(K,J);q=K.prototype;q.target=l;q.relatedTarget=l;q.offsetX=0;q.offsetY=0;q.clientX=0;q.clientY=0;q.screenX=0;q.screenY=0;q.button=0;q.keyCode=0;q.charCode=0;q.ctrlKey=m;q.altKey=m;q.shiftKey=m;q.metaKey=m;q.La=m;q.Z=l;
q.O=function(a,b){var c=this.type=a.type;J.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(E){var f;a:{try{Ta(d.nodeName);f=k;break a}catch(e){}f=m}f||(d=l)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=F||a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=F||a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.La=Ia?a.metaKey:a.ctrlKey;this.state=a.state;this.Z=a;a.defaultPrevented&&this.preventDefault();delete this.w};
q.preventDefault=function(){K.e.preventDefault.call(this);var a=this.Z;if(a.preventDefault)a.preventDefault();else if(a.returnValue=m,Sa)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};q.c=function(){};var Ua=0;function Va(){}q=Va.prototype;q.key=0;q.m=m;q.H=m;q.O=function(a,b,c,d,f,e){if("function"==t(a))this.ma=k;else if(a&&a.handleEvent&&"function"==t(a.handleEvent))this.ma=m;else throw Error("Invalid listener argument");this.j=a;this.oa=b;this.src=c;this.type=d;this.capture=!!f;this.$=e;this.H=m;this.key=++Ua;this.m=m};q.handleEvent=function(a){return this.ma?this.j.call(this.$||this.src,a):this.j.handleEvent.call(this.j,a)};function Wa(a,b){for(var c in a)b.call(h,a[c],c,a)}var Xa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ya(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<Xa.length;e++)c=Xa[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Za={},L={},M={},N={};
function $a(a,b,c,d,f){if("array"==t(b)){for(var e=0;e<b.length;e++)$a(a,b[e],c,d,f);return l}a:{if(!b)throw Error("Invalid event type");d=!!d;var g=L;b in g||(g[b]={d:0,b:0});g=g[b];d in g||(g[d]={d:0,b:0},g.d++);var g=g[d],e=w(a),n;g.b++;if(g[e]){n=g[e];for(var p=0;p<n.length;p++)if(g=n[p],g.j==c&&g.$==f){if(g.m)break;n[p].H=m;a=n[p];break a}}else n=g[e]=[],g.d++;p=ab();g=new Va;g.O(c,p,a,b,d,f);g.H=m;p.src=a;p.j=g;n.push(g);M[e]||(M[e]=[]);M[e].push(g);a.addEventListener?(a==s||!a.ha)&&a.addEventListener(b,
p,d):a.attachEvent(b in N?N[b]:N[b]="on"+b,p);a=g}b=a.key;Za[b]=a;return b}function ab(){var a=bb,b=Ra?function(c){return a.call(b.src,b.j,c)}:function(c){c=a.call(b.src,b.j,c);if(!c)return c};return b}function cb(a,b,c,d,f){if("array"==t(b))for(var e=0;e<b.length;e++)cb(a,b[e],c,d,f);else{d=!!d;a:{e=L;if(b in e&&(e=e[b],d in e&&(e=e[d],a=w(a),e[a]))){a=e[a];break a}a=l}if(a)for(e=0;e<a.length;e++)if(a[e].j==c&&a[e].capture==d&&a[e].$==f){db(a[e].key);break}}}
function db(a){var b=Za[a];if(!b||b.m)return m;var c=b.src,d=b.type,f=b.oa,e=b.capture;c.removeEventListener?(c==s||!c.ha)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in N?N[d]:N[d]="on"+d,f);c=w(c);M[c]&&(f=M[c],xa(f,b),0==f.length&&delete M[c]);b.m=k;if(b=L[d][e][c])b.na=k,eb(d,e,c,b);delete Za[a];return k}
function eb(a,b,c,d){if(!d.P&&d.na){for(var f=0,e=0;f<d.length;f++)d[f].m?d[f].oa.src=l:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.na=m;0==e&&(delete L[a][b][c],L[a][b].d--,0==L[a][b].d&&(delete L[a][b],L[a].d--),0==L[a].d&&delete L[a])}}function fb(a){var b=0;if(a!=l){if(a=w(a),M[a]){a=M[a];for(var c=a.length-1;0<=c;c--)db(a[c].key),b++}}else Wa(Za,function(a,c){db(c);b++})}
function gb(a,b,c,d,f){var e=1;b=w(b);if(a[b]){var g=--a.b,n=a[b];n.P?n.P++:n.P=1;try{for(var p=n.length,T=0;T<p;T++){var r=n[T];r&&!r.m&&(e&=hb(r,f)!==m)}}finally{a.b=Math.max(g,a.b),n.P--,eb(c,d,b,n)}}return Boolean(e)}function hb(a,b){a.H&&db(a.key);return a.handleEvent(b)}
function bb(a,b){if(a.m)return k;var c=a.type,d=L;if(!(c in d))return k;var d=d[c],f,e;if(!Ra){var g;if(!(g=b))a:{g=["window","event"];for(var n=s;f=g.shift();)if(n[f]!=l)n=n[f];else{g=l;break a}g=n}f=g;g=k in d;n=m in d;if(g){if(0>f.keyCode||f.returnValue!=h)return k;a:{var p=m;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(T){p=k}if(p||f.returnValue==h)f.returnValue=k}}p=new K;p.O(f,this);f=k;try{if(g){for(var r=[],u=p.currentTarget;u;u=u.parentNode)r.push(u);e=d[k];e.b=e.d;for(var D=r.length-1;!p.w&&
0<=D&&e.b;D--)p.currentTarget=r[D],f&=gb(e,r[D],c,k,p);if(n){e=d[m];e.b=e.d;for(D=0;!p.w&&D<r.length&&e.b;D++)p.currentTarget=r[D],f&=gb(e,r[D],c,m,p)}}else f=hb(a,p)}finally{r&&(r.length=0)}return f}c=new K(b,this);return f=hb(a,c)};function O(){z.call(this)}y(O,z);q=O.prototype;q.ha=k;q.Q=l;q.da=function(a){this.Q=a};q.addEventListener=function(a,b,c,d){$a(this,a,b,c,d)};q.removeEventListener=function(a,b,c,d){cb(this,a,b,c,d)};
q.dispatchEvent=function(a){var b=a.type||a,c=L;if(b in c){if(v(a))a=new J(a,this);else if(a instanceof J)a.target=a.target||this;else{var d=a;a=new J(b,this);Ya(a,d)}var d=1,f,c=c[b],b=k in c,e;if(b){f=[];for(e=this;e;e=e.Q)f.push(e);e=c[k];e.b=e.d;for(var g=f.length-1;!a.w&&0<=g&&e.b;g--)a.currentTarget=f[g],d&=gb(e,f[g],a.type,k,a)&&a.S!=m}if(m in c)if(e=c[m],e.b=e.d,b)for(g=0;!a.w&&g<f.length&&e.b;g++)a.currentTarget=f[g],d&=gb(e,f[g],a.type,m,a)&&a.S!=m;else for(f=this;!a.w&&f&&e.b;f=f.Q)a.currentTarget=
f,d&=gb(e,f,a.type,m,a)&&a.S!=m;a=Boolean(d)}else a=k;return a};q.c=function(){O.e.c.call(this);fb(this);this.Q=l};function ib(a,b){z.call(this);this.D=a||1;this.G=b||jb;this.U=x(this.Pa,this);this.ba=ha()}y(ib,O);ib.prototype.enabled=m;var jb=s;q=ib.prototype;q.a=l;q.setInterval=function(a){this.D=a;this.a&&this.enabled?(this.stop(),this.start()):this.a&&this.stop()};q.Pa=function(){if(this.enabled){var a=ha()-this.ba;0<a&&a<0.8*this.D?this.a=this.G.setTimeout(this.U,this.D-a):(this.dispatchEvent(kb),this.enabled&&(this.a=this.G.setTimeout(this.U,this.D),this.ba=ha()))}};
q.start=function(){this.enabled=k;this.a||(this.a=this.G.setTimeout(this.U,this.D),this.ba=ha())};q.stop=function(){this.enabled=m;this.a&&(this.G.clearTimeout(this.a),this.a=l)};q.c=function(){ib.e.c.call(this);this.stop();delete this.G};var kb="tick";var lb,mb=!C||C&&9<=I;!E&&!C||C&&C&&9<=I||E&&H("1.9.1");C&&H("9");function nb(a){a=a.className;return v(a)&&a.match(/\S+/g)||[]}function ob(a,b){for(var c=nb(a),d=za(arguments,1),f=c.length+d.length,e=c,g=0;g<d.length;g++)0<=ua(e,d[g])||e.push(d[g]);a.className=c.join(" ");return c.length==f}function pb(a,b){var c=nb(a),d=za(arguments,1),c=qb(c,d);a.className=c.join(" ")}function qb(a,b){return wa(a,function(a){return!(0<=ua(b,a))})};function rb(a,b){this.width=a;this.height=b}rb.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};function sb(a,b){var c=b||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):c.getElementsByClassName?c.getElementsByClassName(a):tb("*",a,b)}
function tb(a,b,c){var d=document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},f=0,e=0,g;g=c[e];e++)a==g.nodeName&&(d[f++]=g);d.length=f;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(e=f=0;g=c[e];e++)a=g.className,"function"==typeof a.split&&0<=ua(a.split(/\s+/),b)&&(d[f++]=g);d.length=f;return d}return c}
function ub(a,b){Wa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in vb?a.setAttribute(vb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var vb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function wb(a,b,c){var d=arguments,f=document,e=d[0],g=d[1];if(!mb&&g&&(g.name||g.type)){e=["<",e];g.name&&e.push(' name="',ma(g.name),'"');if(g.type){e.push(' type="',ma(g.type),'"');var n={};Ya(n,g);delete n.type;g=n}e.push(">");e=e.join("")}e=f.createElement(e);g&&(v(g)?e.className=g:"array"==t(g)?ob.apply(l,[e].concat(g)):ub(e,g));2<d.length&&xb(f,e,d);return e}
function xb(a,b,c){function d(c){c&&b.appendChild(v(c)?a.createTextNode(c):c)}for(var f=2;f<c.length;f++){var e=c[f];if(aa(e)&&!(ba(e)&&0<e.nodeType)){var g;a:{if(e&&"number"==typeof e.length){if(ba(e)){g="function"==typeof e.item||"string"==typeof e.item;break a}if("function"==t(e)){g="function"==typeof e.item;break a}}g=m}va(g?ya(e):e,d)}else d(e)}}function yb(a){a&&a.parentNode&&a.parentNode.removeChild(a)}function P(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function Q(a){this.K=a||s.document||document}Q.prototype.M=function(a){return v(a)?this.K.getElementById(a):a};Q.prototype.createElement=function(a){return this.K.createElement(a)};Q.prototype.createTextNode=function(a){return this.K.createTextNode(String(a))};Q.prototype.appendChild=function(a,b){a.appendChild(b)};function R(a){z.call(this);this.Aa=a;this.aa=[]}y(R,z);var zb=[];function S(a,b,c,d){"array"!=t(c)&&(zb[0]=c,c=zb);for(var f=0;f<c.length;f++){var e=$a(b,c[f],d||a,m,a.Aa||a);a.aa.push(e)}}function Ab(a){va(a.aa,db);a.aa.length=0}R.prototype.c=function(){R.e.c.call(this);Ab(this)};R.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Bb(a,b){J.call(this,"navigate");this.Ta=a;this.Ea=b}y(Bb,J);function U(a,b,c,d){z.call(this);if(a&&!b)throw Error("Can't use invisible history without providing a blank page.");var f;c?f=c:(f="history_state"+Cb,document.write(la(Db,f,f)),f=v(f)?document.getElementById(f):f);this.B=f;this.f=c?P(c)?P(c).parentWindow||P(c).defaultView:window:window;this.xa=this.f.location.href.split("#")[0];this.N=b;C&&!b&&(this.N="https"==window.location.protocol?"https:///":'javascript:""');this.a=new ib(Eb);b=ga(ka,this.a);this.F||(this.F=[]);this.F.push(x(b,h));this.o=!a;
this.l=new R(this);if(a||V)d?a=d:(a="history_iframe"+Cb,d=this.N?'src="'+ma(this.N)+'"':"",document.write(la(Fb,a,d)),a=v(a)?document.getElementById(a):a),this.r=a,this.ra=k;V&&(S(this.l,this.f,"load",this.Ha),this.pa=this.X=m);this.o?Gb(this,W(this),k):X(this,this.B.value);Cb++}y(U,O);U.prototype.A=m;U.prototype.v=m;U.prototype.t=l;var Hb=C&&C&&8<=I||E&&H("1.9.2")||F&&H("532.1"),V=C&&!(C&&8<=I),Ib=V;q=U.prototype;q.u=l;q.c=function(){U.e.c.call(this);this.l.q();Jb(this,m)};
function Jb(a,b){if(b!=a.A)if(V&&!a.X)a.pa=b;else if(b)if(Ga?S(a.l,a.f.document,Kb,a.Ka):E&&S(a.l,a.f,"pageshow",a.Ja),Hb&&a.o)S(a.l,a.f,"hashchange",a.Ia),a.A=k,a.dispatchEvent(new Bb(W(a),m));else{if(!C||a.X)S(a.l,a.a,kb,x(a.ga,a,k)),a.A=k,V||(a.t=W(a),a.dispatchEvent(new Bb(W(a),m))),a.a.start()}else a.A=m,Ab(a.l),a.a.stop()}q.Ha=function(){this.X=k;this.B.value&&X(this,this.B.value,k);Jb(this,this.pa)};q.Ja=function(a){a.Z.persisted&&(Jb(this,m),Jb(this,k))};
q.Ia=function(){var a=Lb(this.f);a!=this.t&&Mb(this,a,k)};function W(a){return a.u!=l?a.u:a.o?Lb(a.f):Nb(a)||""}function Lb(a){a=a.location.href;var b=a.indexOf("#");return 0>b?"":a.substring(b+1)}function Ob(a,b){W(a)!=b&&(a.o?(Gb(a,b,m),Hb||C&&X(a,b,m,h),a.A&&a.ga(m)):(X(a,b,m),a.u=a.t=a.B.value=b,a.dispatchEvent(new Bb(b,m))))}function Gb(a,b,c){var d=a.f.location;a=a.xa;var f=-1!=d.href.indexOf("#");if(Ib||f||b)a+="#"+b;a!=d.href&&(c?d.replace(a):d.href=a)}
function X(a,b,c,d){if(a.ra||b!=Nb(a))if(a.ra=m,b=encodeURIComponent(String(b)),C){var f=a.r.contentDocument||a.r.contentWindow.document;f.open("text/html",c?"replace":h);f.write(la(Pb,ma(d||a.f.document.title),b));f.close()}else if(b=a.N+"#"+b,a=a.r.contentWindow)c?a.location.replace(b):a.location.href=b}
function Nb(a){if(C)return a=a.r.contentDocument||a.r.contentWindow.document,a.body?decodeURIComponent(a.body.innerHTML.replace(/\+/g," ")):l;var b=a.r.contentWindow;if(b){var c;try{c=decodeURIComponent(Lb(b).replace(/\+/g," "))}catch(d){return a.v||(a.v!=k&&a.a.setInterval(Qb),a.v=k),l}a.v&&(a.v!=m&&a.a.setInterval(Eb),a.v=m);return c||l}return l}
q.ga=function(a){if(this.o){var b=Lb(this.f);b!=this.t&&Mb(this,b,a)}if(!this.o||V)if(b=Nb(this)||"",this.u==l||b==this.u)this.u=l,b!=this.t&&Mb(this,b,a)};function Mb(a,b,c){a.t=a.B.value=b;a.o?(V&&X(a,b),Gb(a,b)):X(a,b);a.dispatchEvent(new Bb(W(a),c))}q.Ka=function(){this.a.stop();this.a.start()};
var Kb=["mousedown","keydown","mousemove"],Pb="<title>%s</title><body>%s</body>",Fb='<iframe id="%s" style="display:none" %s></iframe>',Db='<input type="text" name="%s" id="%s" style="display:none">',Cb=0,Eb=150,Qb=1E4;function Rb(a,b,c){var d;a:if(d=sa(c),a.style[d]===h&&(c=(F?"Webkit":E?"Moz":C?"ms":Ga?"O":l)+ta(c),a.style[c]!==h)){d=c;break a}d&&(a.style[d]=b)}
function Sb(a){var b;a:{b=P(a);if(b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,l))){b=b.display||b.getPropertyValue("display")||"";break a}b=""}if("none"!=(b||(a.currentStyle?a.currentStyle.display:l)||a.style&&a.style.display))return Tb(a);b=a.style;var c=b.display,d=b.visibility,f=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=Tb(a);b.display=c;b.position=f;b.visibility=d;return a}
function Tb(a){var b=a.offsetWidth,c=a.offsetHeight,d=F&&!b&&!c;return(b===h||d)&&a.getBoundingClientRect?(b=a.getBoundingClientRect(),C&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop),new rb(b.right-b.left,b.bottom-b.top)):new rb(b,c)};function Y(){}Y.ja=function(){return Y.la?Y.la:Y.la=new Y};Y.prototype.Ga=0;Y.ja();function Z(a){z.call(this);this.Y=a||lb||(lb=new Q);this.Ma=Ub}y(Z,O);Z.prototype.Ca=Y.ja();var Ub=l;q=Z.prototype;q.ka=l;q.s=m;q.h=l;q.Ma=l;q.Fa=l;q.R=l;q.I=l;q.z=l;q.sa=m;q.M=function(){return this.h};q.da=function(a){if(this.R&&this.R!=a)throw Error("Method not supported");Z.e.da.call(this,a)};q.W=function(a){this.h=a};q.L=function(){this.s=k;Vb(this,function(a){!a.s&&a.M()&&a.L()})};function Wb(a){Vb(a,function(a){a.s&&Wb(a)});a.i&&Ab(a.i);a.s=m}
q.c=function(){this.s&&Wb(this);this.i&&(this.i.q(),delete this.i);Vb(this,function(a){a.q()});!this.sa&&this.h&&yb(this.h);this.R=this.Fa=this.h=this.z=this.I=l;Z.e.c.call(this)};function Vb(a,b){a.I&&va(a.I,b,h)}
q.removeChild=function(a,b){if(a){var c=v(a)?a:a.ka||(a.ka=":"+(a.Ca.Ga++).toString(36));a=this.z&&c?(c in this.z?this.z[c]:h)||l:l;if(c&&a){var d=this.z;c in d&&delete d[c];xa(this.I,a);b&&(Wb(a),a.h&&yb(a.h));c=a;if(c==l)throw Error("Unable to set parent component");c.R=l;Z.e.da.call(c,l)}}if(!a)throw Error("Child is not in parent component");return a};function $(a,b){Z.call(this,b);var c=a||{};this.Da="isCalculateHeight"in c?c.isCalculateHeight:k;this.k="cssNamespace"in c?c.cssNamespace:Xb;this.ca="paramName"in c?c.paramName:"tab";this.T=[];this.p=[];this.J={};this.V=[];this.n=0;this.g={Qa:this.k,ta:this.k+"-"+Yb,ea:this.k+"-"+Zb,ua:this.k+"-"+$b,va:this.k+"-"+ac,fa:this.k+"-"+bc,wa:this.k+"-"+cc};dc===h&&(c=wb("input",{id:"history_state",style:"display:none;",type:"hidden"}),document.body.appendChild(c),dc=new U(m,l,c),Jb(dc,k));this.C=dc}var dc;
y($,Z);var Xb="gweb-tabset",Yb="content",Zb="content-active",$b="contents",ac="nav",bc="nav-active",cc="visible";
$.prototype.W=function(a){$.e.W.call(this,a);this.h=a;a=this.M();this.qa=tb("div",this.g.va,a)[0];this.T=tb("li",l,this.qa);this.ya=tb("div",this.g.ua,a)[0];this.p=sb(this.g.ta,a);a=0;for(var b;b=this.p[a];a++)b=b.id||"UNDEFINED-CONTENT-ITEM-"+a,this.J[b]=a,this.V[a]=b;this.n=ec(this);fc(this,this.n,m);S(this.i||(this.i=new R(this)),this.C,"navigate",this.Ba);this.Da&&(a=this.ya,b=gc(this)+"px",v("min-height")?Rb(a,b,"min-height"):Wa("min-height",ga(Rb,a)));ob(this.M(),this.g.wa)};
$.prototype.L=function(){$.e.L.call(this);for(var a=this.i||(this.i=new R(this)),b=0,c;c=this.T[b];b++)c=tb("a",l,c)[0],S(a,c,"click",ga(this.za,b))};$.prototype.Ba=function(a){var b=ec(this);b!=this.n&&a.Ea&&fc(this,b,m)};$.prototype.za=function(a,b){b.preventDefault();fc(this,a,k)};function ec(a){var b;b=RegExp(a.ca+"=[A-Za-z0-9_-]+","g");var c=W(a.C).match(b);if(c&&c[0])for(var d=c.length,f=0;f<d;f++)if(b=c[f].split("=")[1],b in a.J)return b in a.J?a.J[b]:h;return 0}
function gc(a){var b=Sb(a.qa).height,c=Sb(a.p[0]).height;va(a.p,function(a,b){0<b&&(c=Math.max(c,Sb(a).height))},a);return Math.max(b,c)}function fc(a,b,c){c=c!==h?c:k;pb(a.T[a.n],a.g.fa);pb(a.p[a.n],a.g.ea);ob(a.T[b],a.g.fa);ob(a.p[b],a.g.ea);if(c){var d=RegExp(a.ca+"="+a.V[a.n],"g");c=a.ca+"="+a.V[b];var f=W(a.C);(d=f.match(d))&&d[0]?(c=f.replace(d[0],c),Ob(a.C,c)):Ob(a.C,f+(f?"&"+c:c))}a.n=b;a.dispatchEvent(new hc(a))}function hc(a){J.call(this,ic);this.Sa=a}y(hc,J);var ic="tab-select";
new function(a){a=a||{};this.Na=sb("cssNamespace"in a?a.cssNamespace:Xb);this.Oa=[];for(var b=0,c;c=this.Na[b];b++){var d=new $(a);this.Oa.push(d);if(d.s)throw Error("Component already rendered");if(c){d.sa=k;if(!d.Y||d.Y.K!=P(c))d.Y=c?new Q(P(c)):lb||(lb=new Q);d.W(c);d.L()}else throw Error("Invalid element to decorate");}}({isCalculateHeight:m});
})()