(function(g){var window=this;var Jqa=function(a,b){return g.Xb(a,b)},u6=function(a,b,c){a.l.set(b,c)},v6=function(a){u6(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.D)()).toString(36));
return a},w6=function(a,b,c){g.La(c)||(c=[String(c)]);
g.Ym(a.l,b,c)},Kqa=function(a,b){var c=[];
g.$i(b,function(d){try{var e=g.bo.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Da(e)?g.ao(e)&&c.push(d):c.push(d)},a);
return c},Lqa=function(a,b){var c=Kqa(a,b);
(0,g.z)(c,function(d){g.bo.prototype.remove.call(this,d)},a)},x6=function(a){if(a.cd){if(a.cd.locationOverrideToken)return{locationOverrideToken:a.cd.locationOverrideToken};
if(null!=a.cd.latitudeE7&&null!=a.cd.longitudeE7)return{latitudeE7:a.cd.latitudeE7,longitudeE7:a.cd.longitudeE7}}return null},Mqa=function(a,b){g.bb(a,b)||a.push(b)},y6=function(a){var b=0,c;
for(c in a)b++;return b},z6=function(a,b){var c=b instanceof g.Ac?b:g.Fc(b,/^data:image\//i.test(b));
a.src=g.Bc(c)},A6=function(){},Nqa=function(a){try{return g.u.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Oqa=function(a){if(a.Hc&&"function"==typeof a.Hc)return a.Hc();
if(g.Ea(a))return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Tb(a)},Pqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||g.Ea(a))(0,g.z)(a,b,void 0);else{if(a.ae&&"function"==typeof a.ae)var c=a.ae();else if(a.Hc&&"function"==typeof a.Hc)c=void 0;else if(g.Ma(a)||g.Ea(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Ub(a);d=Oqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Qqa=function(a,b,c,d){var e=new g.Mm(null,void 0);
a&&g.Nm(e,a);b&&g.Om(e,b);c&&g.Pm(e,c);d&&(e.i=d);return e},B6=function(a,b){g.dp[a]=!0;
var c=g.bp();c&&c.publish.apply(c,arguments);g.dp[a]=!1},C6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Jm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Rqa(this,a.capabilities||""),Sqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},Rqa=function(a,b){a.capabilities.clear();
(0,g.Xd)(b.split(","),g.Sa(Jqa,Tqa)).forEach(function(c){a.capabilities.add(c)})},Sqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},D6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},E6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},F6=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Uqa=function(a){return new D6(a)},G6=function(a){return g.La(a)?(0,g.A)(a,Uqa):[]},H6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},I6=function(a){return g.La(a)?"["+(0,g.A)(a,H6).join(",")+"]":"null"},J6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Vqa=function(a){return(0,g.A)(a,function(b){return{key:b.id,
name:b.name}})},K6=function(a,b){return g.Za(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},L6=function(a,b){return g.Za(a,function(c){return E6(c,b)})},M6=function(a){try{var b=(0,g.it)(),c=(0,g.ht)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},Wqa=function(){var a=(0,g.ht)();
a&&Lqa(a,a.g.ff(!0))},N6=function(){var a=g.kt("yt-remote-connected-devices")||[];
g.sb(a);return a},Xqa=function(a){if(g.cb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.A)(a,function(d,e){return 0==e?d:d.substring(c.length)})},O6=function(a){g.jt("yt-remote-connected-devices",a,86400)},Q6=function(){if(P6)return P6;
var a=g.kt("yt-remote-device-id");a||(a=J6(),g.jt("yt-remote-device-id",a,31536E3));for(var b=N6(),c=1,d=a;g.bb(b,d);)c++,d=a+"#"+c;return P6=d},R6=function(){var a=N6(),b=Q6();
g.bb(a,b);g.lt()&&g.ub(a,b);a=Xqa(a);if(g.cb(a))try{g.Pr("remote_sid")}catch(c){}else try{g.Or("remote_sid",a.join(","),-1)}catch(c){}},S6=function(){return g.kt("yt-remote-session-browser-channel")},T6=function(){return g.kt("yt-remote-local-screens")||[]},U6=function(){g.jt("yt-remote-lounge-token-expiration",!0,86400)},Yqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.A)(T6(),function(d){return d.loungeToken}),c=(0,g.A)(a,function(d){return d.loungeToken});
(0,g.ch)(c,function(d){return!g.bb(b,d)})&&U6();
g.jt("yt-remote-local-screens",a,31536E3)},Zqa=function(a,b){g.jt("yt-remote-session-browser-channel",a);
g.jt("yt-remote-session-screen-id",b);var c=N6(),d=Q6();g.bb(c,d)||c.push(d);O6(c);R6()},V6=function(a){a||(M6("yt-remote-session-screen-id"),M6("yt-remote-session-video-id"));
R6();a=N6();g.fb(a,Q6());O6(a)},$qa=function(){if(!W6){var a=g.mo();
a&&(W6=new g.Wn(a))}return W6?!!W6.get("yt-remote-use-staging-server"):!1},ara=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},bra=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},X6=function(a){a.length?cra(a.shift(),function(){X6(a)}):Y6()},dra=function(a){return"chrome-extension://"+a+"/cast_sender.js"},cra=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},Y6=function(){var a=bra();
a&&a(!1,"No cast extension found")},fra=function(){if(era){var a=2,b=bra(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;cra("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",Y6,c)}},gra=function(){fra();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);X6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},Z6=function(a,b,c){g.I.call(this);
this.A=null!=c?(0,g.x)(a,c):a;this.Uc=b;this.u=(0,g.x)(this.PC,this);this.g=!1;this.i=0;this.l=this.Ca=null;this.o=[]},$6=function(a){if(g.u.JSON)try{return g.u.JSON.parse(a)}catch(b){}return Nqa(a)},a7=function(){},b7=function(){},hra=function(){},jra=function(a){return(a=ira(a))?new ActiveXObject(a):new XMLHttpRequest},ira=function(a){if(!a.i&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.i=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.i},c7=function(a,b,c,d){this.g=a;
this.l=b;this.C=c;this.A=d||1;this.o=45E3;this.ca=new g.jZ(this);this.i=new g.il;this.i.setInterval(250)},lra=function(a,b,c){a.Ph=1;
a.Qf=v6(b.clone());a.kh=c;a.u=!0;kra(a,null)},d7=function(a,b,c,d,e){a.Ph=1;
a.Qf=v6(b.clone());a.kh=null;a.u=c;e&&(a.Iz=!1);kra(a,d)},kra=function(a,b){a.wi=(0,g.D)();
e7(a);a.xg=a.Qf.clone();w6(a.xg,"t",a.A);a.Ok=0;a.tc=a.g.hp(a.g.Ak()?b:null);0<a.Mp&&(a.An=new g.ll((0,g.x)(a.GA,a,a.tc),a.Mp));a.ca.da(a.tc,"readystatechange",a.QL);var c=a.Sg?g.ec(a.Sg):{};a.kh?(a.fo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.xg,a.fo,a.kh,c)):(a.fo="GET",a.Iz&&!g.Nd&&(c.Connection="close"),a.tc.send(a.xg,a.fo,null,c));a.g.te(1)},ora=function(a,b,c){for(var d=!0;!a.Hg&&a.Ok<c.length;){var e=mra(a,c);
if(e==f7){4==b&&(a.hg=4,g7(15),d=!1);break}else if(e==nra){a.hg=4;g7(16);d=!1;break}else h7(a,e)}4==b&&0==c.length&&(a.hg=1,g7(17),d=!1);a.ue=a.ue&&d;d||(i7(a),j7(a))},mra=function(a,b){var c=a.Ok,d=b.indexOf("\n",c);
if(-1==d)return f7;c=Number(b.substring(c,d));if(isNaN(c))return nra;d+=1;if(d+c>b.length)return f7;var e=b.substr(d,c);a.Ok=d+c;return e},qra=function(a,b){a.wi=(0,g.D)();
e7(a);var c=b?window.location.hostname:"";a.xg=a.Qf.clone();u6(a.xg,"DOMAIN",c);u6(a.xg,"t",a.A);try{a.ze=new ActiveXObject("htmlfile")}catch(n){i7(a);a.hg=7;g7(22);j7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in k7)k=k7[l];else if(l in pra)k=k7[l]=pra[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
k7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Tc(g.tc("b/12014412"),d+"</body></html>");a.ze.open();a.ze.write(g.Oc(c));a.ze.close();a.ze.parentWindow.m=(0,g.x)(a.hL,a);a.ze.parentWindow.d=(0,g.x)(a.Py,a,!0);a.ze.parentWindow.rpcClose=(0,g.x)(a.Py,a,!1);c=a.ze.createElement("DIV");a.ze.parentWindow.document.body.appendChild(c);d=g.Ec(a.xg.toString());d=g.ad(g.Cc(d));d=g.Tc(g.tc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Vc(c,d);a.g.te(1)},e7=function(a){a.Ds=(0,g.D)()+a.o;
rra(a,a.o)},rra=function(a,b){if(null!=a.Ki)throw Error("WatchDog timer not null");
a.Ki=l7((0,g.x)(a.qL,a),b)},m7=function(a){a.Ki&&(g.u.clearTimeout(a.Ki),a.Ki=null)},j7=function(a){a.g.Fv()||a.Hg||a.g.sn(a)},i7=function(a){m7(a);
g.Di(a.An);a.An=null;a.i.stop();g.lZ(a.ca);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.ze&&(a.ze=null)},h7=function(a,b){try{a.g.Jy(a,b),a.g.te(4)}catch(c){}},tra=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;sra(a,b,function(k){k?c(!0):g.u.setTimeout(function(){tra(a,b,c,d,f)},f)})}},sra=function(a,b,c){var d=new Image;
d.onload=function(){try{n7(d),c(!0)}catch(e){}};
d.onerror=function(){try{n7(d),c(!1)}catch(e){}};
d.onabort=function(){try{n7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{n7(d),c(!1)}catch(e){}};
g.u.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
z6(d,a)},n7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},ura=function(a){this.g=a;
this.i=new a7},vra=function(a){var b=o7(a.g,a.Vi,"/mail/images/cleardot.gif");
v6(b);tra(b.toString(),5E3,(0,g.x)(a.UB,a),3,2E3);a.te(1)},q7=function(a){var b=a.g.F;
if(null!=b)g7(5),b?(g7(11),p7(a.g,a,!1)):(g7(12),p7(a.g,a,!0));else if(a.Dd=new c7(a,void 0,void 0,void 0),a.Dd.Sg=a.Kp,b=a.g,b=o7(b,b.Ak()?a.yj:null,a.Lp),g7(5),!g.Ld||g.od(10))w6(b,"TYPE","xmlhttp"),d7(a.Dd,b,!1,a.yj,!1);else{w6(b,"TYPE","html");var c=a.Dd;a=!!a.yj;c.Ph=3;c.Qf=v6(b.clone());qra(c,a)}},r7=function(a){g.yk.call(this);
this.headers=new g.Jm;this.N=a||null;this.i=!1;this.S=this.g=null;this.Z=this.D="";this.u=0;this.l="";this.o=this.ba=this.C=this.R=!1;this.A=0;this.F=null;this.X="";this.I=this.T=!1},wra=function(a){return g.Ld&&g.nd(9)&&g.Ga(a.timeout)&&g.Da(a.ontimeout)},xra=function(a){return"content-type"==a.toLowerCase()},zra=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;yra(a);s7(a)},yra=function(a){a.R||(a.R=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},Bra=function(a){if(a.i&&"undefined"!=typeof g.pZ)if(a.S[1]&&4==t7(a)&&2==a.getStatus())u7(a,"Local request error detected and ignored");
else if(a.C&&4==t7(a))g.jl(a.Hv,0,a);else if(a.dispatchEvent("readystatechange"),4==t7(a)){u7(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.xf(1,String(a.D));if(!f&&g.u.self&&g.u.self.location){var k=g.u.self.location.protocol;f=k.substr(0,k.length-1)}e=!Ara.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<t7(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";yra(a)}}finally{s7(a)}}},s7=function(a,b){if(a.g){Cra(a);
var c=a.g,d=a.S[0]?g.Ia:null;a.g=null;a.S=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},Cra=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.F&&(g.u.clearTimeout(a.F),a.F=null)},t7=function(a){return a.g?a.g.readyState:0},v7=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},u7=function(a,b){return b+" ["+a.Z+" "+a.D+" "+a.getStatus()+"]"},w7=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new a7;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},Dra=function(a,b){this.g=a;
this.map=b;this.context=null},Era=function(a){g.Zj.call(this,"statevent",a)},Fra=function(a,b){g.Zj.call(this,"timingevent",a);
this.size=b},Gra=function(a){g.Zj.call(this,"serverreachability",a)},Jra=function(a){Hra(a);
if(3==a.g){var b=a.fk++,c=a.Rl.clone();u6(c,"SID",a.l);u6(c,"RID",b);u6(c,"TYPE","terminate");x7(a,c);b=new c7(a,a.l,b,void 0);b.Ph=2;b.Qf=v6(c.clone());z6(new Image,b.Qf.toString());b.wi=(0,g.D)();e7(b)}Ira(a)},Kra=function(a){a.oC(1,0);
a.Rl=o7(a,null,a.Jp);y7(a)},Hra=function(a){a.Wf&&(a.Wf.abort(),a.Wf=null);
a.Ob&&(a.Ob.cancel(),a.Ob=null);a.gf&&(g.u.clearTimeout(a.gf),a.gf=null);z7(a);a.yd&&(a.yd.cancel(),a.yd=null);a.fg&&(g.u.clearTimeout(a.fg),a.fg=null)},Lra=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new Dra(a.uH++,b));2!=a.g&&3!=a.g||y7(a)},y7=function(a){a.yd||a.fg||(a.fg=l7((0,g.x)(a.Oy,a),0),a.Ih=0)},Nra=function(a,b){if(1==a.g){if(!b){a.fk=Math.floor(1E5*Math.random());
var c=a.fk++,d=new c7(a,"",c,void 0);d.Sg=null;var e=A7(a),f=a.Rl.clone();u6(f,"RID",c);u6(f,"CVER","1");x7(a,f);lra(d,f,e);a.yd=d;a.g=2}}else 3==a.g&&(b?Mra(a,b):0==a.i.length||a.yd||Mra(a))},Mra=function(a,b){if(b)if(6<a.Ig){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.fk-1;var d=A7(a)}else c=b.C,d=b.kh;else c=a.fk++,d=A7(a);var e=a.Rl.clone();u6(e,"SID",a.l);u6(e,"RID",c);u6(e,"AID",a.bi);x7(a,e);c=new c7(a,a.l,c,a.Ih+1);c.Sg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.yd=c;lra(c,e,d)},x7=function(a,b){if(a.Rc){var c=a.Rc.dv();
c&&g.Nb(c,function(d,e){u6(b,e,d)})}},A7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Ig&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Ig?e:f-d;try{g.Nb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},Ora=function(a){a.Ob||a.gf||(a.C=1,a.gf=l7((0,g.x)(a.Ny,a),0),a.Ch=0)},B7=function(a){if(a.Ob||a.gf||3<=a.Ch)return!1;
a.C++;a.gf=l7((0,g.x)(a.Ny,a),Pra(a,a.Ch));a.Ch++;return!0},p7=function(a,b,c){a.co=c;
a.De=b.vf;a.A||Kra(a)},z7=function(a){null!=a.Lg&&(g.u.clearTimeout(a.Lg),a.Lg=null)},Pra=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},C7=function(a,b){if(2==b||9==b){var c=null;
a.Rc&&(c=null);var d=(0,g.x)(a.vM,a);c||(c=new g.Mm("//www.google.com/images/cleardot.gif"),v6(c));sra(c.toString(),1E4,d)}else g7(2);Qra(a,b)},Qra=function(a,b){a.g=0;
a.Rc&&a.Rc.fu(b);Ira(a);Hra(a)},Ira=function(a){a.g=0;
a.De=-1;if(a.Rc)if(0==a.o.length&&0==a.i.length)a.Rc.So();else{g.jb(a.o);var b=g.jb(a.i);a.o.length=0;a.i.length=0;a.Rc.So(b)}},o7=function(a,b,c){var d=g.Um(c);
if(""!=d.g)b&&g.Om(d,b+"."+d.g),g.Pm(d,d.u);else{var e=window.location;d=Qqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.ij&&g.Nb(a.ij,function(f,k){u6(d,k,f)});
u6(d,"VER",a.Ig);x7(a,d);return d},l7=function(a,b){if(!g.Na(a))throw Error("Fn must not be null and must be a function");
return g.u.setTimeout(function(){a()},b)},g7=function(a){D7.dispatchEvent(new Era(D7,a))},Rra=function(){},Sra=function(){this.g=[];
this.i=[]},Tra=function(a,b){this.action=a;
this.params=b||{}},E7=function(a,b){g.I.call(this);
this.g=new g.K(this.YK,0,this);g.J(this,this.g);this.Uc=5E3;this.i=0;if(g.Na(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Na(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},F7=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Tn;this.i=new E7(this.aM,this);this.g=null;this.ib=!1;this.u=null;this.F="";this.D=this.o=0;this.C=[];this.I=c||!1},Ura=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.co,sessionId:a.g.l,arrayId:a.g.bi}},Vra=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&Nra(a.g),Jra(a.g));a.D=0},G7=function(a){return!!a.g&&3==a.g.g},Wra=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},H7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.xf(4,a))||"";b&&(this.port=":"+b);this.domain=g.yf(a)||"";a=g.Lb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Kb(a,"10.0")&&(this.i=!1))},I7=function(a,b){var c=a.g;
if(g.Da(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Hf(c+b,{})},J7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.o,d,!0),onError:g.Sa(a.l,e),Od:g.Sa(a.u,e)};c&&(a.ub=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Wp(b,a)},$ra=function(){var a=Xra;
Yra();K7.push(a);Zra(K7)},L7=function(a,b){Yra();
var c=K7,d=asa(a,String(b));g.cb(c)?bsa(d):(Zra(c),(0,g.z)(c,function(e){e(d)}))},Yra=function(){K7||(K7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",K7,void 0))},bsa=function(a){var b=(M7+1)%50;
M7=b;N7[b]=a;O7||(O7=49==b)},Zra=function(a){var b=N7;
if(b[0]){var c=M7,d=O7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.z)(a,function(f){f(e)})}while(d!=c);
N7=Array(50);M7=-1;O7=!1}},asa=function(a,b){var c=((0,g.D)()-csa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},P7=function(a){g.O.call(this);
this.C=a;this.g=[]},dsa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},esa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Xd)(a.g,function(f){return!!K6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=dsa(a,b[d])||c;return c},fsa=function(a,b){var c=a.g.length;
a.g=(0,g.Xd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},Q7=function(a,b,c,d){g.O.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Ca=NaN},S7=function(a){P7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;R7(this);this.info("Initializing with "+I6(this.g))},gsa=function(a){if(a.g.length){var b=(0,g.A)(a.g,function(d){return d.id}),c=I7(a.l,"/pairing/get_lounge_token_batch");
J7(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.ZC,a),(0,g.x)(a.YC,a))}},R7=function(a){var b=G6(T6());
b=(0,g.Xd)(b,function(c){return!c.uuid});
return esa(a,b)},T7=function(a,b){Yqa((0,g.A)(a.g,F6));
b&&U6()},V7=function(a,b){g.O.call(this);
this.A=b;var c=g.kt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.bb(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;U7("Initialized with "+g.Aj(this.g))},hsa=function(a,b,c){var d=I7(a.u,"/pairing/get_screen_availability");
J7(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},W7=function(a,b){a:if(y6(b)!=y6(a.g))var c=!1;
else{c=g.Ub(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(U7("Updated online screens: "+g.Aj(a.g)),a.g=b,a.O("screenChange"));isa(a)},X7=function(a){isNaN(a.l)||g.ap(a.l);
a.l=g.Zo((0,g.x)(a.Lr,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},U7=function(a){L7("OnlineScreenService",a)},jsa=function(a){var b={};
(0,g.z)(a.A(),function(c){c.token?b[c.token]=c.id:this.Hb("Requesting availability of screen w/o lounge token.")});
return b},isa=function(a){a=g.Ub(g.Ob(a.g,function(b){return b}));
g.sb(a);a.length?g.jt("yt-remote-online-screen-ids",a.join(","),60):M6("yt-remote-online-screen-ids")},Y7=function(a){P7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};ksa(this)},msa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Ld();if(k=(c?L6(k,c):null)||L6(k,b)){k.uuid=b;var l=Z7(a,k);hsa(a.i,l,function(m){e(m?l:null)})}else c?lsa(a,c,(0,g.x)(function(m){var n=Z7(this,new D6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));hsa(this.i,n,function(q){e(q?n:null)})},a),f):e(null)},nsa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},lsa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ub:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Wp(I7(a.A,"/pairing/get_lounge_token_batch"),e)},osa=function(a){a.g=a.l.Ld();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+I6(a.g))},ksa=function(a){$7(a);
a.l=new S7(a.A);a.l.subscribe("screenChange",(0,g.x)(a.hD,a));osa(a);a.o=G6(g.kt("yt-remote-automatic-screen-cache")||[]);$7(a);a.info("Initializing automatic screens: "+I6(a.o));a.i=new V7(a.A,(0,g.x)(a.Ld,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.O("onlineScreenChange")},a))},Z7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=L6(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.jt("yt-remote-automatic-screen-cache",(0,g.A)(a.o,F6)));$7(a);a.u[b.uuid]=b.id;g.jt("yt-remote-device-id-map",a.u,31536E3);return b},$7=function(a){a.u=g.kt("yt-remote-device-id-map")||{}},a8=function(a,b,c){g.O.call(this);
this.S=c;this.F=a;this.i=b;this.l=null},b8=function(a,b){L7(a.S,b)},c8=function(a,b){a8.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.x)(this.dN,this);this.u=(0,g.x)(this.BL,this);this.o=g.Zo((0,g.x)(function(){psa(this,null)},this),12E4)},qsa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Aj(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ia,(0,g.x)(function(){b8(this,"Failed to send message: getMdxSessionStatus.")},a)):b8(a,"Sending yt message without session: "+g.Aj(b))},psa=function(a,b){g.ap(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.un,a),d=(0,g.x)(a.Nd,a);a.Av(b,c,d,5)}}else a.Nd(Error("Waiting for session status timed out."))},d8=function(a,b,c){a8.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.N=c;this.u=null;this.C=g.Ia;this.A=NaN;this.I=(0,g.x)(this.gN,this);this.g=g.Ia},rsa=function(a){a.g=a.F.MA(a.H,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ia;
this.un(b)},a),(0,g.x)(function(b){this.g=g.Ia;
this.Nd(b)},a))},ssa=function(a){var b={};
b.pairingCode=a.H;b.theme=a.N;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}$qa()&&(b.env_useStageMdx=1);return g.Ff(b)},e8=function(a,b){a8.call(this,a,b,"ManualSession");
this.g=g.Zo((0,g.x)(this.ci,this,null),150)},f8=function(a,b,c,d){g.O.call(this);
this.i=a;this.C=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.gK,this)},tsa=function(a,b){return b?g.Za(a.l,function(c){return E6(b,c.label)},a):null},g8=function(a){L7("Controller",a)},Xra=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},h8=function(a){return a.u||!!a.l.length||!!a.g},i8=function(a,b,c){b!=a.g&&(g.Di(a.g),(a.g=b)?(c?a.O("yt-remote-cast2-receiver-resumed",b.i):a.O("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.My,a,b)),b.l?a.O("yt-remote-cast2-session-change",b.l):c&&a.g.ci(null)):a.O("yt-remote-cast2-session-change",null))},usa=function(a){var b=a.i.LA(),c=a.g&&a.g.i;
a=(0,g.A)(b,function(d){c&&E6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=tsa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Asa=function(a,b,c,d,e,f,k){vsa()?wsa(b,e,f,k)&&(k8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?xsa(a,c):(window.__onGCastApiAvailable=function(l,m){l?xsa(a,c):(l8("Failed to load cast API: "+m),m8(!1),k8(!1),M6("yt-remote-cast-available"),M6("yt-remote-cast-receiver"),ysa(),c(!1))},d?g.lp("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?gra():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?Y6():(fra(),X6(zsa.map(dra))))):j8("Cannot initialize because not running Chrome")},ysa=function(){j8("dispose");
var a=n8();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);Bsa(!1);g.gp(o8);o8.length=0},p8=function(){return!!g.kt("yt-remote-cast-installed")},Csa=function(){var a=g.kt("yt-remote-cast-receiver");
return a?a.friendlyName:null},Dsa=function(){j8("clearCurrentReceiver");
M6("yt-remote-cast-receiver")},Esa=function(){return p8()?n8()?n8().getCastSession():(l8("getCastSelector: Cast is not initialized."),null):(l8("getCastSelector: Cast API is not installed!"),null)},r8=function(){p8()?n8()?q8()?(j8("Requesting cast selector."),n8().requestSession()):(j8("Wait for cast API to be ready to request the session."),o8.push(g.fp("yt-remote-cast2-api-ready",r8))):l8("requestCastSelector: Cast is not initialized."):l8("requestCastSelector: Cast API is not installed!")},s8=
function(a,b){q8()?n8().setConnectedScreenStatus(a,b):l8("setConnectedScreenStatus called before ready.")},vsa=function(){var a=0<=g.Lb.search(/ (CrMo|Chrome|CriOS)\//);
return g.$w||a},Fsa=function(a,b){n8().init(a,b)},wsa=function(a,b,c,d){var e=!1;
n8()||(a=new f8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.jt("yt-remote-cast-available",f);B6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){j8("onReceiverSelected: "+f.friendlyName);
g.jt("yt-remote-cast-receiver",f);B6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){j8("onReceiverResumed: "+f.friendlyName);
g.jt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){j8("onSessionChange: "+H6(f));
f||M6("yt-remote-cast-receiver");B6("yt-remote-cast2-session-change",f)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
j8("cloudview.createSingleton_: "+e);return e},n8=function(){return g.w("yt.mdx.remote.cloudview.instance_")},xsa=function(a,b){m8(!0);
k8(!1);Fsa(a,function(c){c?(Bsa(!0),g.ip("yt-remote-cast2-api-ready")):(l8("Failed to initialize cast API."),m8(!1),M6("yt-remote-cast-available"),M6("yt-remote-cast-receiver"),ysa());b(c)})},j8=function(a){L7("cloudview",a)},l8=function(a){L7("cloudview",a)},m8=function(a){j8("setCastInstalled_ "+a);
g.jt("yt-remote-cast-installed",a)},q8=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},Bsa=function(a){j8("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},k8=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},t8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.C=0;this.g=null;this.hasNext=this.Ee=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},u8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ee=!1;a.hasNext=!1;a.C=0;a.A=(0,g.D)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},v8=function(a){return 1==a.playerState?((0,g.D)()-a.A)/1E3:0},w8=function(a,b){a.C=b;
a.A=(0,g.D)()},x8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.A)/1E3+a.C;
case -1E3:return 0}return a.C},y8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&u8(a)},z8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.fc(a.g);b.hasPrevious=a.Ee;b.hasNext=a.hasNext;b.playerTime=a.C;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},B8=function(a,b){g.O.call(this);
this.g=0;this.o=a;this.A=[];this.u=new Sra;this.l=this.i=null;this.F=(0,g.x)(this.dI,this);this.C=(0,g.x)(this.ik,this);this.D=(0,g.x)(this.cI,this);this.H=(0,g.x)(this.qI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Gs,this),Gsa(this))):c=3;0!=c&&(b?this.Gs(c):g.Zo((0,g.x)(function(){this.Gs(c)},this),0));
var d=Esa();d&&A8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},C8=function(a){return new t8(a.o.getPlayerContextData())},Gsa=function(a){(0,g.z)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Sa(this.dK,b),this))},a)},Hsa=function(a){(0,g.z)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},D8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},F8=function(a,b,c){var d=C8(a);
w8(d,c);-1E3!=d.playerState&&(d.playerState=b);E8(a,d)},G8=function(a,b,c){a.o.sendMessage(b,c)},E8=function(a,b){Hsa(a);
a.o.setPlayerContextData(z8(b));Gsa(a)},A8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.C),a.ik(null));
a.l=b;a.l&&(L7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.C),a.l.media.length&&a.ik(a.l.media[0]))},Isa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=C8(a);b.contentId!=d.videoId&&L7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;w8(d,a.i.getEstimatedTime());E8(a,d)}else L7("CP","No cast media video. Ignoring state update.")},H8=function(a,b,c){return(0,g.x)(function(d){this.Hb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Hb("Retrying "+b+" using MDx browser channel."),G8(this,b,c))},a)},I8=function(a,b,c){g.O.call(this);
this.u=NaN;this.I=!1;this.D=this.C=this.F=this.H=NaN;this.S=[];this.o=this.A=this.l=this.Pa=this.g=null;this.R=a;this.S.push(g.tr(window,"beforeunload",(0,g.x)(this.SC,this)));this.i=[];this.Pa=new t8;this.N=b.id;this.g=Jsa(this,c);this.g.subscribe("handlerOpened",this.hI,this);this.g.subscribe("handlerClosed",this.eI,this);this.g.subscribe("handlerError",this.fI,this);this.g.subscribe("handlerMessage",this.gI,this);Wra(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Pa.videoId;
g.lt()&&g.jt("yt-remote-session-video-id",d)},this)},J8=function(a){L7("conn",a)},Jsa=function(a,b){return new F7(I7(a.R,"/bc"),b)},K8=function(a,b){a.O("proxyStateChange",b)},Ksa=function(a){a.u=g.Zo((0,g.x)(function(){J8("Connecting timeout");
this.Gh(1)},a),2E4)},L8=function(a){g.ap(a.u);
a.u=NaN},M8=function(a){g.ap(a.H);
a.H=NaN},Lsa=function(a){N8(a);
a.F=g.Zo((0,g.x)(function(){O8(this,"getNowPlaying")},a),2E4)},N8=function(a){g.ap(a.F);
a.F=NaN},Nsa=function(a,b){b&&(L8(a),M8(a));
b==(G7(a.g)&&isNaN(a.u))?b&&(K8(a,1),O8(a,"getSubtitlesTrack")):b?(a.yv()&&a.Pa.reset(),K8(a,1),O8(a,"getNowPlaying"),Msa(a)):a.Gh(1)},Osa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Pa.videoId&&(g.$b(b.params)?a.Pa.g=null:a.Pa.g=b.params,a.O("remotePlayerChange"))},Psa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Pa.listId=b.params.listId||a.Pa.listId;y8(a.Pa,c,d);a.O("remoteQueueChange")},Rsa=function(a,b){b.params=b.params||{};
Psa(a,b);Qsa(a,b);a.O("autoplayDismissed")},Qsa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
w8(a.Pa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Pa.playerState&&(c=-1E3);a.Pa.playerState=c;c=Number(b.params.loadedTime);a.Pa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Pa.D=isNaN(c)?0:c;c=a.Pa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Pa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Pa.playerState?Lsa(a):N8(a);a.O("remotePlayerChange")},Ssa=function(a,b){if(-1E3!=
a.Pa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Pa.playerState=c;c=parseInt(b.params.currentTime,10);w8(a.Pa,isNaN(c)?0:c);a.O("remotePlayerChange")}},Tsa=function(a,b){var c="true"==b.params.muted;
a.Pa.volume=parseInt(b.params.volume,10);a.Pa.muted=c;a.O("remotePlayerChange")},Usa=function(a,b){a.A=b.params.videoId;
a.O("nowAutoplaying",parseInt(b.params.timeout,10))},Vsa=function(a,b){var c="true"==b.params.hasNext;
a.Pa.Ee="true"==b.params.hasPrevious;a.Pa.hasNext=c;a.O("previousNextChange")},Msa=function(a){g.ap(a.D);
a.D=g.Zo((0,g.x)(a.Gh,a,1),864E5)},O8=function(a,b,c){c?J8("Sending: action="+b+", params="+g.Aj(c)):J8("Sending: action="+b);
a.g.sendMessage(b,c)},P8=function(a){P7.call(this,"ScreenServiceProxy");
this.Tc=a;this.i=[];this.i.push(this.Tc.$_s("screenChange",(0,g.x)(this.bN,this)));this.i.push(this.Tc.$_s("onlineScreenChange",(0,g.x)(this.IJ,this)))},$sa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Ro("MDX_CONFIG")||b;Wqa();R6();Q8||(Q8=new H7(b?b.loungeApiHost:void 0),$qa()&&(Q8.g="/api/loungedev"));R8||(R8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",R8,void 0));Wsa();var c=S8();if(!c){var d=new Y7(Q8);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=S8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Asa(a,d,function(m){m?T8()&&s8(T8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){B6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),U8("Initializing: "+g.Aj(b)),V8.push(g.fp("yt-remote-cast2-availability-change",function(){B6("yt-remote-receiver-availability-change")})),V8.push(g.fp("yt-remote-cast2-receiver-selected",function(){W8(null);
B6("yt-remote-auto-connect","cast-selector-receiver")})),V8.push(g.fp("yt-remote-cast2-receiver-resumed",function(){B6("yt-remote-receiver-resumed","cast-selector-receiver")})),V8.push(g.fp("yt-remote-cast2-session-change",Xsa)),V8.push(g.fp("yt-remote-connection-change",function(m){m?s8(T8(),"YouTube TV"):X8()||(s8(null,null),Dsa())})),a=Y8(),b.isAuto&&(a.id+="#dial"),g.Np("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),U8(" -- with channel params: "+
g.Aj(a)),Ysa(a),c.start(),T8()||Zsa())},bta=function(){var a=ata();
p8()&&g.kt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},ata=function(){var a=S8().Tc.$_gos();
var b=Z8();b&&$8()&&(K6(a,b)||a.push(b));return Vqa(a)},a9=function(){var a=cta();
!a&&p8()&&Csa()&&(a={key:"cast-selector-receiver",name:Csa()});return a},cta=function(){var a=ata(),b=Z8();
b||(b=X8());return g.Za(a,function(c){return b&&E6(b,c.key)?!0:!1})},Z8=function(){var a=T8();
if(!a)return null;var b=S8().Ld();return L6(b,a)},Xsa=function(a){U8("remote.onCastSessionChange_: "+H6(a));
if(a){var b=Z8();b&&b.id==a.id?s8(b.id,"YouTube TV"):(b&&b9(),c9(a,1))}else $8()&&b9()},b9=function(){q8()?n8().stopSession():l8("stopSession called before API ready.");
var a=$8();a&&(a.disconnect(1),d9(null))},e9=function(){var a=$8();
return!!a&&3!=a.getProxyState()},U8=function(a){L7("remote",a)},S8=function(){if(!f9){var a=g.w("yt.mdx.remote.screenService_");
f9=a?new P8(a):null}return f9},T8=function(){return g.w("yt.mdx.remote.currentScreenId_")},dta=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},eta=function(){return g.w("yt.mdx.remote.connectData_")},W8=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},$8=function(){return g.w("yt.mdx.remote.connection_")},d9=function(a){var b=$8();
W8(null);a||dta("");g.Ha("yt.mdx.remote.connection_",a,void 0);R8&&((0,g.z)(R8,function(c){c(a)}),R8.length=0);
b&&!a?B6("yt-remote-connection-change",!1):!b&&a&&B6("yt-remote-connection-change",!0)},X8=function(){var a=g.lt();
if(!a)return null;var b=S8().Ld();return L6(b,a)},c9=function(a,b){Z8()&&Z8();
if(g9)h9=a;else{dta(a.id);var c=new I8(Q8,a,Y8());c.connect(b,eta());c.subscribe("beforeDisconnect",function(d){B6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){$8()&&d9(null)});
d9(c)}},Zsa=function(){var a=X8();
a?(U8("Resume connection to: "+H6(a)),c9(a,0)):(V6(),Dsa(),U8("Skipping connecting because no session screen found."))},Wsa=function(){var a=Y8();
if(g.$b(a)){a=Q6();var b=g.kt("yt-remote-session-name")||"",c=g.kt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},Y8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Ysa=function(a){a?(g.jt("yt-remote-session-app",a.app),g.jt("yt-remote-session-name",a.name)):(M6("yt-remote-session-app"),M6("yt-remote-session-name"));
g.Ha("yt.mdx.remote.channelParams_",a,void 0)},i9=function(a,b,c){g.I.call(this);
this.u=a;this.i=b;this.l=new g.ks(this);g.J(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.eJ);this.l.K(b,"captionschanged",this.bI);this.l.K(b,"captionssettingschanged",this.Zz);this.l.K(b,"videoplayerreset",this.vn);this.l.K(b,"mdxautoplaycancel",this.TB);this.R=this.l.K(b,"onVolumeChange",this.uy);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Iy,this);c.subscribe("remotePlayerChange",this.kk,this);c.subscribe("remoteQueueChange",this.vn,this);c.subscribe("autoplayUpNext",this.iy,
this);c.subscribe("previousNextChange",this.Fy,this);c.subscribe("nowAutoplaying",this.Ay,this);c.subscribe("autoplayDismissed",this.hy,this);this.suggestion=null;this.F=new g.pC(64);this.o=new g.K(this.Xz,500,this);g.J(this,this.o);this.A=new g.K(this.Yz,1E3,this);g.J(this,this.A);this.I=new Z6(this.EM,0,this);g.J(this,this.I);this.C={};this.S=new g.K(this.yA,1E3,this);g.J(this,this.S);this.H=new g.ll(this.xF,1E3,this);g.J(this,this.H);this.N=g.Ia;this.Zz();this.vn();this.kk()},j9=function(a,b){var c=
a.u,d=a.i.getVideoData().lengthSeconds;
c.S=b||0;c.player.O("progresssync",b,d)},fta=function(a){j9(a,0);
a.o.stop();k9(a,new g.pC(64))},m9=function(a,b){if(l9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.hc(c,b));a.g.Nz(a.i.getVideoData(1).videoId,c);a.C=C8(a.g).g}},n9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Ge,x6(c));k9(a,new g.pC(1))},gta=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{CQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},l9=function(a){return C8(a.g).videoId==a.i.getVideoData(1).videoId},k9=function(a,b){a.A.stop();
var c=a.F;if(!g.vC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.CK(a.i,d);a.F=b;hta(a.u,c,b)}},o9=function(){g.W.call(this,{B:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{B:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{B:"div",G:"ytp-mdx-popup-title",U:"You're signed out"},{B:"div",G:"ytp-mdx-popup-description",U:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{B:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{B:"button",V:["ytp-button","ytp-mdx-privacy-popup-cancel"],U:"Cancel"},{B:"button",V:["ytp-button","ytp-mdx-privacy-popup-confirm"],
U:"Confirm"}]}]}]});this.l=new g.mL(this,250);g.J(this,this.l);this.C=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.C,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},p9=function(a){g.W.call(this,{B:"div",
G:"ytp-remote",J:[{B:"div",G:"ytp-remote-display-status",J:[{B:"div",G:"ytp-remote-display-status-icon",J:[g.oL()]},{B:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.mL(this,250);g.J(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);ita(this,g.yK(a))},ita=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.TL("Error on $RECEIVER_NAME",c):g.wC(b)||g.U(b,4)?g.TL("Playing on $RECEIVER_NAME",c):g.TL("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},q9=function(a,b){g.PN.call(this,"Play on",0,a,b);
this.l=a;this.C={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},r9=function(a){g.YO.call(this,a);
this.i={key:J6(),name:"This computer"};this.u=null;this.o=[];this.N=this.g=null;this.H=[this.i];this.l=this.i;this.C=new g.pC(64);this.S=0;this.F=-1;this.A=null;if(!g.Yy(this.player.M())){a=this.player;var b=g.jD(a);b&&(b=b.Zm())&&(b=new q9(a,b),g.J(this,b));b=new p9(a);g.J(this,b);g.UK(a,b.element,4);this.A=new o9;g.J(this,this.A);g.UK(a,this.A.element,4);this.I=!!X8()}this.D=null},s9=function(a){a.D&&(a.player.removeEventListener("presentingplayerstatechange",a.D),a.D=null)},hta=function(a,b,c){a.C=
c;
a.player.O("presentingplayerstatechange",new g.AD(c,b))},t9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)b9();
else{var c;(c=!g.Q(a.player.M().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.Ro("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.Ro("SESSION_INDEX")&&!g.Ro("LOGGED_IN")))||a.I||!a.A);if(c?0:"WEB"==a.player.M().deviceParams.c||"WEB_EMBEDDED_PLAYER"==a.player.M().deviceParams.c)g.wC(g.yK(a.player))?a.player.pauseVideo():(a.D=(0,g.x)(a.GL,a),a.player.addEventListener("presentingplayerstatechange",a.D)),a.A&&a.A.l.show(),$8()||(g9=!0);a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ua(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Ge,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=x6(c))&&(d.locationInfo=c);c=d}else c=null;U8("Connecting to: "+g.Aj(b));"cast-selector-receiver"==b.key?(W8(c||null),q8()?n8().setLaunchParams(c||null):l8("setLaunchParams called before ready.")):
!c&&e9()&&T8()==b.key?B6("yt-remote-connection-change",!0):(b9(),W8(c||null),c=S8().Ld(),(c=L6(c,b.key))&&c9(c,1))}},pra={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},k7={"'":"\\'"},jta={},Tqa={AN:"atp",PP:"ska",EP:"que",eP:"mus",OP:"sus",wO:"dsp",LP:"seq"};
C6.prototype.Xf=function(){var a=new C6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var W6,P6="",era=ara("loadCastFramework")||ara("loadCastApplicationFramework"),zsa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Ua(Z6,g.I);g.h=Z6.prototype;g.h.OC=function(a){this.o=arguments;this.g=!1;this.Ca?this.l=(0,g.D)()+this.Uc:this.Ca=g.jl(this.u,this.Uc)};
g.h.stop=function(){this.Ca&&(g.u.clearTimeout(this.Ca),this.Ca=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.W=function(){this.stop();Z6.gb.W.call(this)};
g.h.PC=function(){this.l?(this.Ca=g.jl(this.u,this.l-(0,g.D)()),this.l=null):(this.Ca=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};a7.prototype.stringify=function(a){return g.u.JSON.stringify(a,void 0)};
a7.prototype.parse=function(a){return g.u.JSON.parse(a,void 0)};b7.prototype.g=null;b7.prototype.getOptions=function(){var a;(a=this.g)||(a={},ira(this)&&(a[0]=!0,a[1]=!0),a=this.g=a);return a};var u9;g.Ua(hra,b7);u9=new hra;g.h=c7.prototype;g.h.Sg=null;g.h.ue=!1;g.h.Ki=null;g.h.Ds=null;g.h.wi=null;g.h.Ph=null;g.h.Qf=null;g.h.xg=null;g.h.kh=null;g.h.tc=null;g.h.Ok=0;g.h.ze=null;g.h.fo=null;g.h.hg=null;g.h.zj=-1;g.h.Iz=!0;g.h.Hg=!1;g.h.Mp=0;g.h.An=null;var nra={},f7={};g.h=c7.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.QL=function(a){a=a.target;var b=this.An;b&&3==t7(a)?b.vj():this.GA(a)};
g.h.GA=function(a){try{if(a==this.tc)a:{var b=t7(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Ld&&!g.od(10)||g.Nd&&!g.nd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.eg&&!v7(this.tc))break a;this.Hg||4!=b||7==c||(8==c||0>=d?this.g.te(3):this.g.te(2));m7(this);var e=this.tc.getStatus();this.zj=e;var f=v7(this.tc);(this.ue=200==e)?(4==b&&i7(this),this.u?(ora(this,b,f),g.eg&&this.ue&&3==b&&(this.ca.da(this.i,"tick",this.KL),this.i.start())):h7(this,f),this.ue&&!this.Hg&&(4==b?this.g.sn(this):(this.ue=
!1,e7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.hg=3,g7(13)):(this.hg=0,g7(14)),i7(this),j7(this))}}catch(k){this.tc&&v7(this.tc)}finally{}};
g.h.KL=function(){var a=t7(this.tc),b=v7(this.tc);this.Ok<b.length&&(m7(this),ora(this,a,b),this.ue&&4!=a&&e7(this))};
g.h.hL=function(a){l7((0,g.x)(this.gL,this,a),0)};
g.h.gL=function(a){this.Hg||(m7(this),h7(this,a),e7(this))};
g.h.Py=function(a){l7((0,g.x)(this.fL,this,a),0)};
g.h.fL=function(a){this.Hg||(i7(this),this.ue=a,this.g.sn(this),this.g.te(4))};
g.h.cancel=function(){this.Hg=!0;i7(this)};
g.h.qL=function(){this.Ki=null;var a=(0,g.D)();0<=a-this.Ds?(2!=this.Ph&&this.g.te(3),i7(this),this.hg=2,g7(18),j7(this)):rra(this,this.Ds-a)};
g.h.getLastError=function(){return this.hg};g.h=ura.prototype;g.h.Kp=null;g.h.Dd=null;g.h.Bn=!1;g.h.Gv=null;g.h.Pl=null;g.h.qq=null;g.h.Lp=null;g.h.ee=null;g.h.vf=-1;g.h.yj=null;g.h.Vi=null;g.h.connect=function(a){this.Lp=a;a=o7(this.g,null,this.Lp);g7(3);this.Gv=(0,g.D)();var b=this.g.D;null!=b?(this.yj=b[0],(this.Vi=b[1])?(this.ee=1,vra(this)):(this.ee=2,q7(this))):(w6(a,"MODE","init"),this.Dd=new c7(this,void 0,void 0,void 0),this.Dd.Sg=this.Kp,d7(this.Dd,a,!1,null,!0),this.ee=0)};
g.h.UB=function(a){if(a)this.ee=2,q7(this);else{g7(4);var b=this.g;b.De=b.Wf.vf;C7(b,9)}a&&this.te(2)};
g.h.hp=function(a){return this.g.hp(a)};
g.h.abort=function(){this.Dd&&(this.Dd.cancel(),this.Dd=null);this.vf=-1};
g.h.Fv=function(){return!1};
g.h.Jy=function(a,b){this.vf=a.zj;if(0==this.ee)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.De=this.vf;C7(c,2);return}this.yj=c[0];this.Vi=c[1]}else c=this.g,c.De=this.vf,C7(c,2);else if(2==this.ee)if(this.Bn)g7(7),this.qq=(0,g.D)();else if("11111"==b){if(g7(6),this.Bn=!0,this.Pl=(0,g.D)(),c=this.Pl-this.Gv,!g.Ld||g.od(10)||500>c)this.vf=200,this.Dd.cancel(),g7(12),p7(this.g,this,!0)}else g7(8),this.Pl=this.qq=(0,g.D)(),this.Bn=!1};
g.h.sn=function(){this.vf=this.Dd.zj;if(this.Dd.ue)0==this.ee?this.Vi?(this.ee=1,vra(this)):(this.ee=2,q7(this)):2==this.ee&&((!g.Ld||g.od(10)?!this.Bn:200>this.qq-this.Pl)?(g7(11),p7(this.g,this,!1)):(g7(12),p7(this.g,this,!0)));else{0==this.ee?g7(9):2==this.ee&&g7(10);var a=this.g;this.Dd.getLastError();a.De=this.vf;C7(a,2)}};
g.h.Ak=function(){return this.g.Ak()};
g.h.isActive=function(){return this.g.isActive()};
g.h.te=function(a){this.g.te(a)};g.Ua(r7,g.yk);var Ara=/^https?$/i,kta=["POST","PUT"];g.h=r7.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.u=0;this.Z=b;this.R=!1;this.i=!0;this.g=this.N?jra(this.N):jra(u9);this.S=this.N?this.N.getOptions():u9.getOptions();this.g.onreadystatechange=(0,g.x)(this.Hv,this);try{A6(u7(this,"Opening Xhr")),this.ba=!0,this.g.open(b,String(a),!0),this.ba=!1}catch(f){A6(u7(this,"Error opening Xhr: "+f.message));zra(this,f);return}a=c||
"";var e=this.headers.clone();d&&Pqa(d,function(f,k){e.set(k,f)});
d=g.Za(e.ae(),xra);c=g.u.FormData&&a instanceof g.u.FormData;!g.bb(kta,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.T&&(this.g.withCredentials=this.T);try{Cra(this),0<this.A&&(this.I=wra(this.g),A6(u7(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.x)(this.Iv,this)):this.F=g.jl(this.Iv,this.A,this)),A6(u7(this,"Sending request")),this.C=!0,this.g.send(a),this.C=!1}catch(f){A6(u7(this,"Send error: "+f.message)),zra(this,f)}};
g.h.Iv=function(){"undefined"!=typeof g.pZ&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,u7(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(u7(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),s7(this))};
g.h.W=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),s7(this,!0));r7.gb.W.call(this)};
g.h.Hv=function(){this.ga()||(this.ba||this.C||this.o?Bra(this):this.fK())};
g.h.fK=function(){Bra(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<t7(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Ea(this.l)?this.l:String(this.l)};g.h=w7.prototype;g.h.ij=null;g.h.yd=null;g.h.Ob=null;g.h.Jp=null;g.h.Rl=null;g.h.St=null;g.h.im=null;g.h.fk=0;g.h.uH=0;g.h.Rc=null;g.h.fg=null;g.h.gf=null;g.h.Lg=null;g.h.Wf=null;g.h.co=null;g.h.bi=-1;g.h.qw=-1;g.h.De=-1;g.h.Ih=0;g.h.Ch=0;g.h.Ig=8;var D7=new g.yk;g.Ua(Era,g.Zj);g.Ua(Fra,g.Zj);g.Ua(Gra,g.Zj);g.h=w7.prototype;g.h.connect=function(a,b,c,d,e){g7(0);this.Jp=b;this.ij=c||{};d&&g.Da(e)&&(this.ij.OSID=d,this.ij.OAID=e);this.A?(l7((0,g.x)(this.nu,this,a),100),Kra(this)):this.nu(a)};
g.h.nu=function(a){this.Wf=new ura(this);this.Wf.Kp=null;this.Wf.i=this.u;this.Wf.connect(a)};
g.h.Fv=function(){return 0==this.g};
g.h.Oy=function(a){this.fg=null;Nra(this,a)};
g.h.Ny=function(){this.gf=null;this.Ob=new c7(this,this.l,"rpc",this.C);this.Ob.Sg=null;this.Ob.Mp=0;var a=this.St.clone();u6(a,"RID","rpc");u6(a,"SID",this.l);u6(a,"CI",this.co?"0":"1");u6(a,"AID",this.bi);x7(this,a);if(!g.Ld||g.od(10))u6(a,"TYPE","xmlhttp"),d7(this.Ob,a,!0,this.im,!1);else{u6(a,"TYPE","html");var b=this.Ob,c=!!this.im;b.Ph=3;b.Qf=v6(a.clone());qra(b,c)}};
g.h.Jy=function(a,b){if(0!=this.g&&(this.Ob==a||this.yd==a))if(this.De=a.zj,this.yd==a&&3==this.g)if(7<this.Ig){try{var c=this.u.parse(b)}catch(f){c=null}if(g.La(c)&&3==c.length)if(0==c[0])a:{if(!this.gf){if(this.Ob)if(this.Ob.wi+3E3<this.yd.wi)z7(this),this.Ob.cancel(),this.Ob=null;else break a;B7(this);g7(19)}}else this.qw=c[1],0<this.qw-this.bi&&37500>c[2]&&this.co&&0==this.Ch&&!this.Lg&&(this.Lg=l7((0,g.x)(this.XH,this),6E3));else C7(this,11)}else b!=jta.XN.g&&C7(this,11);else if(this.Ob==a&&
z7(this),!g.zb(b)){c=this.u.parse(b);g.La(c);for(var d=0;d<c.length;d++){var e=c[d];this.bi=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.im=e[2],e=e[3],null!=e?this.Ig=e:this.Ig=6,this.g=3,this.Rc&&this.Rc.hu(),this.St=o7(this,this.Ak()?this.im:null,this.Jp),Ora(this)):"stop"==e[0]&&C7(this,7):3==this.g&&("stop"==e[0]?C7(this,7):"noop"!=e[0]&&this.Rc&&this.Rc.gu(e),this.Ch=0)}}};
g.h.XH=function(){null!=this.Lg&&(this.Lg=null,this.Ob.cancel(),this.Ob=null,B7(this),g7(20))};
g.h.sn=function(a){if(this.Ob==a){z7(this);this.Ob=null;var b=2}else if(this.yd==a)this.yd=null,b=1;else return;this.De=a.zj;if(0!=this.g)if(a.ue)1==b?(b=(0,g.D)()-a.wi,D7.dispatchEvent(new Fra(D7,a.kh?a.kh.length:0,b,this.Ih)),y7(this),this.o.length=0):Ora(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.De)){if(d=1==b)this.yd||this.fg||1==this.g||2<=this.Ih?d=!1:(this.fg=l7((0,g.x)(this.Oy,this,a),Pra(this,this.Ih)),this.Ih++,d=!0);d=!(d||2==b&&B7(this))}if(d)switch(c){case 1:C7(this,
5);break;case 4:C7(this,10);break;case 3:C7(this,6);break;case 7:C7(this,12);break;default:C7(this,2)}}};
g.h.oC=function(a){if(!g.bb(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.vM=function(a){a?g7(2):(g7(1),Qra(this,8))};
g.h.hp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new r7;a.T=!1;return a};
g.h.isActive=function(){return!!this.Rc&&this.Rc.isActive(this)};
g.h.te=function(a){D7.dispatchEvent(new Gra(D7,a))};
g.h.Ak=function(){return!(!g.Ld||g.od(10))};
g.h=Rra.prototype;g.h.hu=function(){};
g.h.gu=function(){};
g.h.fu=function(){};
g.h.So=function(){};
g.h.dv=function(){return{}};
g.h.isActive=function(){return!0};g.h=Sra.prototype;g.h.isEmpty=function(){return g.cb(this.g)&&g.cb(this.i)};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.bb(this.g,a)||g.bb(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Ana)(b,a);0<=c?(g.eb(b,c),b=!0):b=!1;return b||g.fb(this.i,a)};
g.h.Hc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};g.Ua(E7,g.I);g.h=E7.prototype;g.h.YK=function(){this.Uc=Math.min(3E5,2*this.Uc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Uc+15E3*Math.random();g.xn(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Uc=5E3};g.Ua(F7,Rra);g.h=F7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Df=function(a){return this.l.Tg(a)};
g.h.O=function(a,b){return this.l.O.apply(this.l,arguments)};
g.h.dispose=function(){this.ib||(this.ib=!0,g.Di(this.l),Vra(this),g.Di(this.i),this.i=null)};
g.h.ga=function(){return this.ib};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new w7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Rc=null);d.Rc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.bi):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.hc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.C.push(c):G7(this)&&Lra(this.g,c)};
g.h.hu=function(){this.i.reset();this.u=null;this.o=0;if(this.C.length){var a=this.C;this.C=[];for(var b=0,c=a.length;b<c;++b)Lra(this.g,a[b])}this.O("handlerOpened")};
g.h.fu=function(a){var b=2==a&&401==this.g.De;4==a||b||this.i.start();this.O("handlerError",a)};
g.h.So=function(a){if(!this.i.isActive())this.O("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.C.push(d)}};
g.h.dv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.hc(a,this.u);return a};
g.h.gu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),Jra(this.g)):this.O("handlerMessage",new Tra(a[0],a[1]))};
g.h.aM=function(){this.i.isActive();var a=this.g,b=0;a.Ob&&b++;a.yd&&b++;0==b&&this.connect(this.u,this.o)};H7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
H7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
H7.prototype.u=function(a){a(Error("request timed out"))};var csa=(0,g.D)(),K7=null,N7=Array(50),M7=-1,O7=!1;g.Ua(P7,g.O);P7.prototype.Ld=function(){return this.g};
P7.prototype.contains=function(a){return!!K6(this.g,a)};
P7.prototype.get=function(a){return a?L6(this.g,a):null};
P7.prototype.info=function(a){L7(this.C,a)};g.r(Q7,g.O);g.h=Q7.prototype;g.h.start=function(){!this.g&&isNaN(this.Ca)&&this.KA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Ca)||(g.ap(this.Ca),this.Ca=NaN)};
g.h.W=function(){this.stop();g.O.prototype.W.call(this)};
g.h.KA=function(){this.Ca=NaN;this.g=g.Wp(I7(this.A,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.ZM,this),onError:(0,g.x)(this.YM,this),Od:(0,g.x)(this.aN,this)})};
g.h.ZM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.O("pairingComplete",new D6(c))};
g.h.YM=function(a){this.g=null;a.status&&404==a.status?this.i>=lta.length?this.O("pairingFailed",Error("DIAL polling timed out")):(a=lta[this.i],this.Ca=g.Zo((0,g.x)(this.KA,this),a),this.i++):this.O("pairingFailed",Error("Server error "+a.status))};
g.h.aN=function(){this.g=null;this.O("pairingFailed",Error("Server not responding"))};
var lta=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ua(S7,P7);g.h=S7.prototype;g.h.start=function(){R7(this)&&this.O("screenChange");!g.kt("yt-remote-lounge-token-expiration")&&gsa(this);g.ap(this.i);this.i=g.Zo((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){R7(this);dsa(this,a);T7(this,!1);this.O("screenChange");b(a);a.token||gsa(this)};
g.h.remove=function(a,b){var c=R7(this);fsa(this,a)&&(T7(this,!1),c=!0);b(a);c&&this.O("screenChange")};
g.h.Yn=function(a,b,c,d){var e=R7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,T7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.O("screenChange")};
g.h.W=function(){g.ap(this.i);S7.gb.W.call(this)};
g.h.ZC=function(a){R7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}T7(this,!b);b&&L7(this.C,"Missed "+b+" lounge tokens.")};
g.h.YC=function(a){L7(this.C,"Requesting lounge tokens failed: "+a)};g.r(V7,g.O);g.h=V7.prototype;g.h.start=function(){var a=parseInt(g.kt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?X7(this):(this.o=(0,g.D)()+3E5,g.jt("yt-remote-fast-check-period",this.o),this.Lr())};
g.h.isEmpty=function(){return g.$b(this.g)};
g.h.update=function(){U7("Updating availability on schedule.");var a=this.A(),b=g.Ob(this.g,function(c,d){return c&&!!L6(a,d)},this);
W7(this,b)};
g.h.W=function(){g.ap(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.O.prototype.W.call(this)};
g.h.Lr=function(){g.ap(this.l);this.l=NaN;this.i&&this.i.abort();var a=jsa(this);if(y6(a)){var b=I7(this.u,"/pairing/get_screen_availability");this.i=J7(this.u,b,{lounge_token:g.Ub(a).join(",")},(0,g.x)(this.BK,this,a),(0,g.x)(this.AK,this))}else W7(this,{}),X7(this)};
g.h.BK=function(a,b){this.i=null;var c=g.Ub(jsa(this));if(g.tb(c,g.Ub(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;W7(this,d);X7(this)}else this.Hb("Changing Screen set during request."),this.Lr()};
g.h.AK=function(a){this.Hb("Screen availability failed: "+a);this.i=null;X7(this)};
g.h.Hb=function(a){L7("OnlineScreenService",a)};g.Ua(Y7,P7);g.h=Y7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.O("screenChange"),this.i.isEmpty()||this.O("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Yn=function(a,b,c,d){this.l.contains(a)?this.l.Yn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,L7(this.C,a),d(Error(a)))};
g.h.Ld=function(a){return a?this.g:g.ib(this.g,(0,g.Xd)(this.o,function(b){return!this.contains(b)},this))};
g.h.LA=function(){return(0,g.Xd)(this.Ld(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.MA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new Q7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.Di(f);d(Z7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Di(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.cN=function(a,b,c,d){g.Wp(I7(this.A,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new D6(f.screen||{});if(!k.name||nsa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);nsa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(Z7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Od:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.W=function(){g.Di(this.l);g.Di(this.i);Y7.gb.W.call(this)};
g.h.hD=function(){osa(this);this.O("screenChange");this.i.update()};
Y7.prototype.dispose=Y7.prototype.dispose;g.Ua(a8,g.O);g.h=a8.prototype;g.h.un=function(a){this.l=a;this.O("sessionScreen",this.l)};
g.h.Nd=function(a){this.ga()||(a&&b8(this,""+a),this.l=null,this.O("sessionScreen",null))};
g.h.info=function(a){L7(this.S,a)};
g.h.OA=function(){return null};
g.h.Tr=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){b8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.W=function(){this.Tr("");a8.gb.W.call(this)};g.Ua(c8,a8);g.h=c8.prototype;g.h.Sr=function(a){if(this.g){if(this.g==a)return;b8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);qsa(this)};
g.h.ci=function(a){this.info("launchWithParams no-op for Cast: "+g.Aj(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Nd()},this),(0,g.x)(function(){this.Nd(Error("Failed to stop receiver app."))},this)):this.Nd(Error("Stopping cast device witout session."))};
g.h.Tr=g.Ia;g.h.W=function(){this.info("disposeInternal");g.ap(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;c8.gb.W.call(this)};
g.h.BL=function(a,b){if(!this.ga())if(b){var c=$6(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Aj(c));switch(d){case "mdxSessionStatus":psa(this,c.screenId);break;default:b8(this,"Unknown youtube message: "+d)}}else b8(this,"Unable to parse message.")}else b8(this,"No data in message.")};
g.h.Av=function(a,b,c,d){msa(this.F,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(b8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Zo((0,g.x)(this.Av,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.OA=function(){return this.g};
g.h.dN=function(a){this.ga()||a||(b8(this,"Cast session died."),this.Nd())};g.Ua(d8,a8);g.h=d8.prototype;g.h.Sr=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.ci=function(a){this.u=a;this.C()};
g.h.stop=function(){this.g();this.g=g.Ia;g.ap(this.A);this.o?this.o.stop((0,g.x)(this.Nd,this,null),(0,g.x)(this.Nd,this,"Failed to stop DIAL device.")):this.Nd()};
g.h.W=function(){this.g();this.g=g.Ia;g.ap(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;d8.gb.W.call(this)};
g.h.gN=function(a){this.ga()||a||(b8(this,"DIAL session died."),this.g(),this.g=g.Ia,this.Nd())};
g.h.Xp=function(a){this.H=J6();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,ssa(this));a(b);rsa(this)}else this.C=(0,g.x)(function(){g.ap(this.A);this.C=g.Ia;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,ssa(this));a(c);rsa(this)},this),this.A=g.Zo((0,g.x)(function(){this.C()},this),100)};
g.h.DD=function(a,b,c){msa(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.un(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Xp(b,c)},this),(0,g.x)(function(d){b8(this,"Failed to get DIAL screen: "+d);
this.Xp(b,c)},this))};g.Ua(e8,a8);e8.prototype.stop=function(){this.Nd()};
e8.prototype.Sr=g.Ia;e8.prototype.ci=function(){g.ap(this.g);this.g=NaN;var a=L6(this.F.Ld(),this.i.label);a?this.un(a):this.Nd(Error("No such screen"))};
e8.prototype.W=function(){g.ap(this.g);this.g=NaN;e8.gb.W.call(this)};g.Ua(f8,g.O);g.h=f8.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.C);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.kK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.Ly,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.yI,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ga()||
(chrome.cast.addReceiverActionListener(this.o),$ra(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.NA,this)),this.l=usa(this),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.x)(function(k){this.Hb("Failed to set initial custom receivers: "+g.Aj(k))},this)),this.O("yt-remote-cast2-availability-change",h8(this)),b(!0))},this),(0,g.x)(function(k){this.Hb("Failed to initialize API: "+g.Aj(k));
b(!1)},this))};
g.h.iM=function(a,b){g8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)g8("Unsetting old screen status: "+this.g.i.friendlyName),i8(this,null)}if(a&&b){if(!this.g){c=L6(this.i.Ld(),a);if(!c){g8("setConnectedScreenStatus: Unknown screen.");return}var d=tsa(this,c);d||(g8("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ia,(0,g.x)(function(e){this.Hb("Failed to set initial custom receivers: "+g.Aj(e))},this)));
g8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);i8(this,new e8(this.i,d),!0)}this.g.Tr(b)}else g8("setConnectedScreenStatus: no screen.")};
g.h.jM=function(a){this.ga()?this.Hb("Setting connection data on disposed cast v2"):this.g?this.g.ci(a):this.Hb("Setting connection data without a session")};
g.h.fN=function(){this.ga()?this.Hb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),i8(this,null)):g8("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.Ly,this),(0,g.x)(this.HK,this))};
g.h.W=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.NA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.fb(g.w("yt.mdx.remote.debug.handlers_")||[],Xra);g.Di(this.g);f8.gb.W.call(this)};
g.h.Hb=function(a){L7("Controller",a)};
g.h.My=function(a,b){this.g==a&&(b||i8(this,null),this.O("yt-remote-cast2-session-change",b))};
g.h.gK=function(a,b){if(!this.ga())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),g8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)g8("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{g8("onReceiverAction_: Casting to active receiver.");this.g.l&&this.O("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:i8(this,
new e8(this.i,a));break;case chrome.cast.ReceiverType.DIAL:i8(this,new d8(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:i8(this,new c8(this.i,a));break;default:this.Hb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Hb("Stopping receiver w/o session: "+a.friendlyName)}else this.Hb("onReceiverAction_ called without receiver.")};
g.h.yI=function(a){if(this.ga())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Hb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Hb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return g8("Reselecting dial screen."),
this.O("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Hb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);i8(this,new d8(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.DD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Xp,b))};
g.h.Ly=function(a){if(!this.ga()){g8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)g8("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),i8(this,new c8(this.i,b),!0);else{this.Hb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=L6(this.i.Ld(),c.label);d&&E6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(g8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Di(this.g),this.g=new c8(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.My,this,this.g)),this.g.ci(null));this.g.Sr(a)}}};
g.h.eN=function(){return this.g?this.g.OA():null};
g.h.HK=function(a){this.ga()||(this.Hb("Failed to estabilish a session: "+g.Aj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&i8(this,null))};
g.h.kK=function(a){g8("Receiver availability updated: "+a);if(!this.ga()){var b=h8(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;h8(this)!=b&&this.O("yt-remote-cast2-availability-change",h8(this))}};
g.h.NA=function(){this.ga()||(this.l=usa(this),g8("Updating custom receivers: "+g.Aj(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.x)(function(){this.Hb("Failed to set custom receivers.")},this)),this.O("yt-remote-cast2-availability-change",h8(this)))};
f8.prototype.setLaunchParams=f8.prototype.jM;f8.prototype.setConnectedScreenStatus=f8.prototype.iM;f8.prototype.stopSession=f8.prototype.fN;f8.prototype.getCastSession=f8.prototype.eN;f8.prototype.requestSession=f8.prototype.requestSession;f8.prototype.init=f8.prototype.init;f8.prototype.dispose=f8.prototype.dispose;var o8=[];t8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";u8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ee=a.hasPrevious,this.hasNext=a.hasNext,this.C=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
t8.prototype.isAdPlaying=function(){return 1081==this.playerState};
t8.prototype.getDuration=function(){return this.u?this.D+v8(this):this.D};
t8.prototype.clone=function(){return new t8(z8(this))};g.r(B8,g.O);g.h=B8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ia,H8(this,"play")):G8(this,"play"),F8(this,1,x8(C8(this))),this.O("remotePlayerChange")):D8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ia,H8(this,"pause")):G8(this,"pause"),F8(this,2,x8(C8(this))),this.O("remotePlayerChange")):D8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=C8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,H8(this,"seekTo",{newTime:a}))}else G8(this,"seekTo",{newTime:a});F8(this,3,a);this.O("remotePlayerChange")}else D8(this,g.Sa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ia,H8(this,"stopVideo")):G8(this,"stopVideo");var a=C8(this);a.index=-1;a.videoId="";u8(a);E8(this,a);this.O("remotePlayerChange")}else D8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=C8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){L7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Hb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){L7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Hb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);G8(this,"setVolume",e)}c.muted=b;c.volume=a;E8(this,c)}else D8(this,g.Sa(this.setVolume,a,b))};
g.h.Nz=function(a,b){if(1==this.g){var c=C8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Aj(b.style),g.hc(d,c.g));G8(this,"setSubtitlesTrack",d);E8(this,c)}else D8(this,g.Sa(this.Nz,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();G8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=C8(this);d.audioTrackId=c;E8(this,d)}else D8(this,g.Sa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=C8(this);c=c||0;var m={videoId:a,currentIndex:c};y8(l,a,c);g.Da(b)&&(w8(l,b),m.currentTime=b);g.Da(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Aj(k));G8(this,"setPlaylist",m);d||E8(this,l)};
g.h.JA=function(a,b){if(1==this.g){if(a&&b){var c=C8(this);y8(c,a,b);E8(this,c)}G8(this,"previous")}else D8(this,g.Sa(this.JA,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=C8(this);y8(c,a,b);E8(this,c)}G8(this,"next")}else D8(this,g.Sa(this.nextVideo,a,b))};
g.h.Hu=function(){1==this.g?G8(this,"dismissAutoplay"):D8(this,this.Hu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.O("proxyStateChange",a,this.g)}g.O.prototype.dispose.call(this)};
g.h.W=function(){Hsa(this);this.o=null;this.u.clear();A8(this,null);g.O.prototype.W.call(this)};
g.h.Gs=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.O("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,g.cb(b.g)&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.dK=function(a,b){this.O(a,b)};
g.h.dI=function(a){if(!a)this.ik(null),A8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=C8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)L7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,E8(this,b)}};
g.h.ik=function(a){L7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),Isa(this),this.O("remotePlayerChange")};
g.h.cI=function(a){a?(Isa(this),this.O("remotePlayerChange")):this.ik(null)};
g.h.qI=function(){var a=Esa();a&&A8(this,a)};
g.h.Hb=function(a){L7("CP",a)};g.r(I8,g.O);g.h=I8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Da(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Da(k)&&(l.currentIndex=k);c&&(this.Pa.listId=c);this.Pa.videoId=d;this.Pa.index=k||0;this.Pa.state=3;w8(this.Pa,m);this.o="UNSUPPORTED";J8("Connecting with setPlaylist and params: "+g.Aj(l));this.g.connect({method:"setPlaylist",
params:g.Aj(l)},a,S6())}else J8("Connecting without params"),this.g.connect({},a,S6());Ksa(this)};
g.h.dispose=function(){this.ga()||(this.O("beforeDispose"),K8(this,3));g.O.prototype.dispose.call(this)};
g.h.W=function(){L8(this);N8(this);M8(this);g.ap(this.C);this.C=NaN;g.ap(this.D);this.D=NaN;this.l=null;g.ur(this.S);this.S.length=0;this.g.dispose();g.O.prototype.W.call(this);this.o=this.A=this.i=this.Pa=this.g=null};
g.h.SC=function(){this.Gh(2)};
g.h.hI=function(){J8("Channel opened");this.I&&(this.I=!1,M8(this),this.H=g.Zo((0,g.x)(function(){J8("Timing out waiting for a screen.");this.Gh(1)},this),15E3));
Zqa(Ura(this.g),this.N)};
g.h.eI=function(){J8("Channel closed");isNaN(this.u)?V6(!0):V6();this.dispose()};
g.h.fI=function(a){V6();isNaN(this.qj())?(J8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,J8("Channel error: "+a+" with reconnection in "+this.qj()+" ms"),K8(this,2))};
g.h.gI=function(a){a.params?J8("Received: action="+a.action+", params="+g.Aj(a.params)):J8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=$6(a.params.devices);this.i=(0,g.A)(a,function(c){return new C6(c)});
a=!!g.Za(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Nsa(this,a);break;case "loungeScreenDisconnected":g.gb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Nsa(this,!1);break;case "remoteConnected":var b=new C6($6(a.params.device));g.Za(this.i,function(c){return b?c.id==b.id:!1})||Mqa(this.i,b);
break;case "remoteDisconnected":b=new C6($6(a.params.device));g.gb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":Psa(this,a);break;case "nowPlaying":Rsa(this,a);break;case "onStateChange":Qsa(this,a);break;case "onAdStateChange":Ssa(this,a);break;case "onVolumeChanged":Tsa(this,a);break;case "onSubtitlesTrackChanged":Osa(this,a);break;case "nowAutoplaying":Usa(this,a);break;case "autoplayDismissed":this.O("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.O("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.O("autoplayModeChange",this.o);"DISABLED"==this.o&&this.O("autoplayDismissed");break;case "onHasPreviousNextChanged":Vsa(this,a);break;case "requestAssistedSignIn":this.O("assistedSignInRequested",a.params.authCode);break;default:J8("Unrecognized action: "+a.action)}};
g.h.XL=function(){if(this.l){var a=this.l;this.l=null;this.Pa.videoId!=a&&O8(this,"getNowPlaying")}};
g.h.IC=function(){var a=3;this.ga()||(a=0,isNaN(this.qj())?G7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Gh=function(a){J8("Disconnecting with "+a);L8(this);this.O("beforeDisconnect",a);1==a&&V6();Vra(this.g,a);this.dispose()};
g.h.HC=function(){var a=this.Pa;this.l&&(a=this.Pa.clone(),y8(a,this.l,a.index));return z8(a)};
g.h.kM=function(a){var b=new t8(a);b.videoId&&b.videoId!=this.Pa.videoId&&(this.l=b.videoId,g.ap(this.C),this.C=g.Zo((0,g.x)(this.XL,this),5E3));var c=[];this.Pa.listId==b.listId&&this.Pa.videoId==b.videoId&&this.Pa.index==b.index||c.push("remoteQueueChange");this.Pa.playerState==b.playerState&&this.Pa.volume==b.volume&&this.Pa.muted==b.muted&&x8(this.Pa)==x8(b)&&g.Aj(this.Pa.g)==g.Aj(b.g)||c.push("remotePlayerChange");this.Pa.reset(a);(0,g.z)(c,function(d){this.O(d)},this)};
g.h.yv=function(){var a=this.g.A.id,b=g.Za(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.qj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
g.h.BC=function(){return this.o||"UNSUPPORTED"};
g.h.CC=function(){return this.A||""};
g.h.XM=function(){if(!isNaN(this.qj())){var a=this.g.i;g.yn(a.g);a.start()}};
g.h.fM=function(a,b){O8(this,a,b);Msa(this)};
I8.prototype.subscribe=I8.prototype.subscribe;I8.prototype.unsubscribeByKey=I8.prototype.Df;I8.prototype.getProxyState=I8.prototype.IC;I8.prototype.disconnect=I8.prototype.Gh;I8.prototype.getPlayerContextData=I8.prototype.HC;I8.prototype.setPlayerContextData=I8.prototype.kM;I8.prototype.getOtherConnectedRemoteId=I8.prototype.yv;I8.prototype.getReconnectTimeout=I8.prototype.qj;I8.prototype.getAutoplayMode=I8.prototype.BC;I8.prototype.getAutoplayVideoId=I8.prototype.CC;I8.prototype.reconnect=I8.prototype.XM;
I8.prototype.sendMessage=I8.prototype.fM;g.r(P8,P7);g.h=P8.prototype;g.h.Ld=function(a){return this.Tc.$_gs(a)};
g.h.contains=function(a){return!!this.Tc.$_c(a)};
g.h.get=function(a){return this.Tc.$_g(a)};
g.h.start=function(){this.Tc.$_st()};
g.h.add=function(a,b,c){this.Tc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Tc.$_r(a,b,c)};
g.h.Yn=function(a,b,c,d){this.Tc.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.i.length;a<b;++a)this.Tc.$_ubk(this.i[a]);this.i.length=0;this.Tc=null;P7.prototype.W.call(this)};
g.h.bN=function(){this.O("screenChange")};
g.h.IJ=function(){this.O("onlineScreenChange")};
Y7.prototype.$_st=Y7.prototype.start;Y7.prototype.$_gspc=Y7.prototype.cN;Y7.prototype.$_gsppc=Y7.prototype.MA;Y7.prototype.$_c=Y7.prototype.contains;Y7.prototype.$_g=Y7.prototype.get;Y7.prototype.$_a=Y7.prototype.add;Y7.prototype.$_un=Y7.prototype.Yn;Y7.prototype.$_r=Y7.prototype.remove;Y7.prototype.$_gs=Y7.prototype.Ld;Y7.prototype.$_gos=Y7.prototype.LA;Y7.prototype.$_s=Y7.prototype.subscribe;Y7.prototype.$_ubk=Y7.prototype.Df;var h9=null,g9=!1,Q8=null,R8=null,f9=null,V8=[];g.r(i9,g.I);g.h=i9.prototype;
g.h.W=function(){g.I.prototype.W.call(this);this.o.stop();this.A.stop();this.I.stop();this.N();this.g.unsubscribe("proxyStateChange",this.Iy,this);this.g.unsubscribe("remotePlayerChange",this.kk,this);this.g.unsubscribe("remoteQueueChange",this.vn,this);this.g.unsubscribe("autoplayUpNext",this.iy,this);this.g.unsubscribe("previousNextChange",this.Fy,this);this.g.unsubscribe("nowAutoplaying",this.Ay,this);this.g.unsubscribe("autoplayDismissed",this.hy,this);this.g=this.u=null};
g.h.Zw=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(l9(this)){if(!C8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==C8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.vj(c[0],c[1]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();n9(this,0==c?void 0:c);break;case "control_seek":n9(this,c[0]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.bI=function(a){this.I.OC(a)};
g.h.EM=function(a){this.Zw("control_subtitles_set_track",g.$b(a)?null:a)};
g.h.Zz=function(){var a=this.i.getOption("captions","track");g.$b(a)||m9(this,a)};
g.h.uy=function(a){if(l9(this)){this.g.unsubscribe("remotePlayerChange",this.kk,this);var b=Math.round(a.volume);a=!!a.muted;var c=C8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.S.start();this.g.subscribe("remotePlayerChange",this.kk,this)}};
g.h.eJ=function(){g.$b(this.C)||gta(this,this.C);this.D=!1};
g.h.Iy=function(a,b){this.A.stop();2==b&&this.Yz()};
g.h.kk=function(){if(l9(this)){this.o.stop();var a=C8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.F=1;break;case 1082:case 1083:this.u.F=0;break;default:this.u.F=-1}switch(a.playerState){case 1081:case 1:k9(this,new g.pC(8));this.Xz();break;case 1085:case 3:k9(this,new g.pC(9));break;case 1083:case 0:k9(this,new g.pC(2));this.H.stop();j9(this,this.i.getVideoData().lengthSeconds);break;case 1084:k9(this,new g.pC(4));break;case 2:k9(this,new g.pC(4));j9(this,x8(a));
break;case -1:k9(this,new g.pC(64));break;case -1E3:k9(this,new g.pC(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=C8(this.g).g;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,gta(this,a));a=C8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.S.isActive()||this.yA()}else fta(this)};
g.h.Fy=function(){this.i.O("mdxpreviousnextchange")};
g.h.vn=function(){l9(this)||fta(this)};
g.h.TB=function(){this.g.Hu()};
g.h.iy=function(a){a&&!g.Q(this.i.M().experiments,"disable_legacy_desktop_remote_queue")&&(a=g.Wp("/watch_queue_ajax",{method:"GET",sd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.kL,this)}))&&(this.N=(0,g.x)(a.abort,a))};
g.h.kL=function(a,b){var c=new g.$A(this.i.M(),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.O("mdxautoplayupnext",c)};
g.h.Ay=function(a){isNaN(a)||this.i.O("mdxnowautoplaying",a)};
g.h.hy=function(){this.i.O("mdxautoplaycanceled")};
g.h.xF=function(a,b){-1==C8(this.g).playerState?n9(this,a):b&&this.g.seekTo(a)};
g.h.yA=function(){if(l9(this)){var a=C8(this.g);this.l.Ra(this.R);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.R=this.l.K(this.i,"onVolumeChange",this.uy)}};
g.h.Xz=function(){this.o.stop();if(!this.g.ga()){var a=C8(this.g);1==a.playerState&&k9(this,new g.pC(8));j9(this,x8(a));this.o.start()}};
g.h.Yz=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.r(o9,g.W);o9.prototype.o=function(){B6("mdx-privacy-popup-cancel");this.l.hide()};
o9.prototype.A=function(){B6("mdx-privacy-popup-confirm");this.l.hide()};g.r(p9,g.W);p9.prototype.u=function(a){ita(this,a.state)};g.r(q9,g.PN);q9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.C=g.vb(a,this.A,this),g.RN(this,(0,g.A)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.je(this.A(a)),this.enable(!0)):this.enable(!1)};
q9.prototype.A=function(a){return a.key};
q9.prototype.se=function(a){return"cast-selector-receiver"==a?"Cast...":this.C[a].name};
q9.prototype.Nc=function(a){g.PN.prototype.Nc.call(this,a);this.l.setOption("remote","currentReceiver",this.C[a]);this.o.kb()};g.r(r9,g.YO);g.h=r9.prototype;
g.h.create=function(){$sa(g.Py(this.player.M()));this.o.push(g.fp("yt-remote-before-disconnect",this.YH,this));this.o.push(g.fp("yt-remote-connection-change",this.lK,this));this.o.push(g.fp("yt-remote-receiver-availability-change",this.Gy,this));this.o.push(g.fp("yt-remote-auto-connect",this.jK,this));this.o.push(g.fp("yt-remote-receiver-resumed",this.iK,this));this.o.push(g.fp("mdx-privacy-popup-confirm",this.NL,this));this.o.push(g.fp("mdx-privacy-popup-cancel",this.ML,this));this.Gy()};
g.h.load=function(){this.player.cancelPlayback();g.YO.prototype.load.call(this);this.u=new i9(this,this.player,this.g);var a=(a=eta())?a.currentTime:0;var b=e9()?new B8($8(),void 0):null;0==a&&b&&(a=x8(C8(b)));0!=a&&(this.S=a||0,this.player.O("progresssync",a,void 0));hta(this,this.C,this.C);g.eS(this.player.app,6)};
g.h.unload=function(){this.player.O("mdxautoplaycanceled");this.l=this.i;g.Ei(this.u,this.g);this.g=this.u=null;g.YO.prototype.unload.call(this);g.eS(this.player.app,5);s9(this)};
g.h.W=function(){g.gp(this.o);g.YO.prototype.W.call(this)};
g.h.Vj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.Zw.apply(this.u,[a].concat(g.fa(c)))};
g.h.getAdState=function(){return this.F};
g.h.KC=function(){return this.loaded?this.u.suggestion:null};
g.h.Ee=function(){return this.g?C8(this.g).Ee:!1};
g.h.hasNext=function(){return this.g?C8(this.g).hasNext:!1};
g.h.getCurrentTime=function(){return this.S};
g.h.getProgressState=function(){var a=C8(this.g),b=this.player.getVideoData();return{allowSeeking:g.Q(this.player.M().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Zb():!a.isAdPlaying()&&this.player.Zb(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+v8(a):a.l,isAtLiveHead:1>=(a.u?a.i+v8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+v8(a):a.i,seekableStart:0<a.o?a.o+v8(a):
a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.kF=function(){this.g&&this.g.JA()};
g.h.YH=function(a){1==a&&(this.N=this.g?C8(this.g):null)};
g.h.lK=function(){var a=e9()?new B8($8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.N=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.Di(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.N)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,x8(a)));this.player.O("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Gy=function(){this.H=[this.i].concat(bta());var a=a9()||this.i;t9(this,a);this.player.ka("onMdxReceiversChange")};
g.h.GL=function(a){!this.I&&g.CD(a,8)&&(this.player.pauseVideo(),s9(this))};
g.h.jK=function(){var a=a9();t9(this,a)};
g.h.iK=function(){this.l=a9()};
g.h.NL=function(){this.I=!0;s9(this);g9=!1;h9&&c9(h9,1);h9=null};
g.h.ML=function(){this.I=!1;s9(this);t9(this,this.i);this.l=this.i;g9=!1;h9=null;this.player.playVideo()};
g.h.xc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?r8():t9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&r8(),!0):!1}};
g.h.lF=function(){G8(this.g,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.If=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.eP.remote=r9;})(_yt_player);
